onepercentclub/bluebottle

- bluebottle/common/static/js/bluebottle/components.js
- bluebottle/common/templates/bluebottle/components.hbs
Added small component for the character count.
> added component logic for char count

- bluebottle/payments_docdata/tests/test_models.py
We now create an address in the save method of a user
> Fix tests which create user addresses BB-2360

- bluebottle/bb_organizations/serializers.py
- bluebottle/bb_organizations/tests/test_api.py
- bluebottle/organizations/serializers.py
...fix tests by setting iban/bic values
> Move iban/bic validation to bb_origanization BB-2363 BB-2358

- .travis.yml
- bluebottle/bb_follow/models.py
- bluebottle/bb_follow/tests/test_models.py
- bluebottle/recurring_donations/management/commands/process_monthly_donations.py
- bluebottle/recurring_donations/tests/test_commands.py
- bluebottle/settings/testing.py
- moved organization serializer code into bb_organization
- cleaned up the follower code a little and fixed follower email for fundraiser
- added iban/bic data to tests
- fixed test for recurring donation
> Various fixes for saas

- bluebottle/utils/staticfiles_finders.py
This should fix errors you get in your console:
AttributeError: 'list' object has no attribute 'rfind'
> Fix static files finder errors

- bluebottle/common/static/sass/base/_modals.scss
- bluebottle/common/static/sass/new-sass/modules/_video.scss
- fix dropdown ie
- fix movie ie
- fix styling modal apply task
> BOOK-1129, BOOK-1124, BOOK-1125

- bluebottle/bb_accounts/models.py
- bluebottle/bb_projects/admin.py
- bluebottle/utils/templates/utils/admin/change_list.html
- Remove a couple of admin pages for models that shouldn't be modified
- Fix extending of template
> BB 2372 admin site

- bluebottle/clients/middleware.py
- bluebottle/clients/tests/test_properties.py
- bluebottle/recurring_donations/permissions.py
- bluebottle/recurring_donations/views.py
- bluebottle/settings/base.py
- Add permission for RecurringDonationsEnabled
- Some code format clean-ups
> Adjust for optional recurring donations property

- bluebottle/pages/fixtures/pages.json
- setup.py
And bump psycopg2 for fluent-content fix
> Add default pages BB-2393

- bluebottle/bb_accounts/admin.py
- bluebottle/pages/models.py
- bluebottle/utils/management/__init__.py
- bluebottle/utils/utils.py
And non-superuser's should not be able to change user to superuser or change user permissions BB-2853
> Add extra page permissions for staff group BB-2697

- bluebottle/bb_accounts/serializers.py
- bluebottle/bb_accounts/tests/test_api.py
Mostly style changes for PEP8. Added 'primary_language' to UserProfile serializer.
> readded primary_language to userProfile serializer

- bluebottle/payments/models.py
- bluebottle/payments/tests/test_models.py
- bluebottle/payments_docdata/adapters.py
Set a proper description on payment reciepts.
> Fix payment reciept text

- bluebottle/bb_donations/admin.py
- bluebottle/payments/admin.py
- bluebottle/payments/models.py
- bluebottle/payments_docdata/admin.py
- bluebottle/payments_docdata/migrations/0005_auto__chg_field_docdatapayment_total_acquirer_pending__chg_field_docda.py
- bluebottle/payments_docdata/migrations/0006_auto__add_field_docdatadirectdebitpayment_customer_id__add_field_docda.py
- bluebottle/payments_docdata/models.py
- bluebottle/payments_docdata/tests/factory_models.py
- bluebottle/payments_docdata/tests/test_models.py
This should do it. Fixed quite a bit more then the ticket specified, see commit messages for that.
> Sa 3095 direct debit unkown

- bluebottle/bb_payouts/models.py
- bluebottle/bb_payouts/signals.py
- bluebottle/payouts/admin.py
- bluebottle/payouts/models.py
And fix some display issues in BO
> Set tenant properties when handling payout signal (triggered by cron job) BB-3294

- bluebottle/bb_accounts/models.py
- bluebottle/bb_projects/models.py
- bluebottle/bb_tasks/models.py
- bluebottle/urls/i18n_urls.py
- dashboard.py
- setup.py
Reverts onepercentclub/bluebottle#1633
> Revert "Maykin/exportdb"

- bluebottle/bb_accounts/models.py
- bluebottle/bb_projects/models.py
- bluebottle/bb_tasks/models.py
- bluebottle/urls/i18n_urls.py
- dashboard.py
- setup.py
Reverts onepercentclub/bluebottle#1634
Yeah.. I know.
> Revert "Revert "Maykin/exportdb""

- bluebottle/bb_tasks/models.py
related to https://github.com/onepercentclub/reef/pull/984
> removed unused property

- bluebottle/bb_projects/fixtures/project_data.json
- bluebottle/bb_projects/migrations/0007_change_project_phase_sequence.py
Small fix to make the sequence of project phases (e.g. in back office) more logical.
> Put voting phases between submitted and campaign

- bluebottle/votes/admin.py
- bluebottle/votes/models.py
- bluebottle/votes/tests/test_api.py
- bluebottle/votes/views.py
- Fixes #BB-4427 (vote for 2nd project)
- Regression test
- Add Vote admin
> Make sure you can vote for more than 1 project

- bluebottle/votes/models.py
> Sort votes by created desc

- bluebottle/bb_donations/tests/test_api.py
- bluebottle/bb_donations/views.py
- bluebottle/projects/models.py
- bluebottle/projects/serializers.py
- bluebottle/projects/tests/test_unit.py
* Add filter in project donation list view
* Pagenate list view
* Correctly calculate supporter count
* Add / fix tests
* Formatting fixes
> Add co-financing filter

- bluebottle/projects/admin.py
- bluebottle/test/factory_models/votes.py
- bluebottle/votes/admin.py
- bluebottle/votes/migrations/0002_auto__add_field_vote_ip_address__chg_field_vote_voter.py
- bluebottle/votes/models.py
- bluebottle/votes/tests/test_api.py
- bluebottle/votes/views.py
* Make vote admin sortable by email
* Make project admin sortable by votes
* Make it possible to export votes to csv
* Add ip_adress of user to vote
* Flake8 stuff
* Tests
> Add vote fraud prevention stuff

- bluebottle/bb_projects/models.py
- bluebottle/projects/models.py
This will improve monthly donation project selection by not showing projects that don't need money.
> Add money_needed as filter.

- bluebottle/auth/middleware.py
- bluebottle/urls/__init__.py
- bluebottle/urls/core.py
...and a little cleanup for admin middleware
> Don't include language with docs

- bluebottle/payments_docdata/gateway.py
- bluebottle/payments_mock/views.py
- bluebottle/projects/models.py
- bluebottle/wallposts/admin.py
This prevents user to get logged out when donating.
We should do a proper fix for the fact that you get logged out when navigating to #!
> Remove #! from some urls

- bluebottle/bb_accounts/tests/test_models.py
- bluebottle/projects/tests/test_api.py
- bluebottle/wallposts/tests/test_api.py
- bluebottle/wallposts/views.py
- remove old / commented wallpost tests
> Check owner permissions when sharing wallpost BB-5174

- bluebottle/bb_accounts/tests/test_models.py
- bluebottle/bb_projects/models.py
- bluebottle/projects/tests/test_api.py
- setup.py
and fix some errors/warnings in tests
> Bump drf/jwt package for security fixes

- bluebottle/news/tests/test_api.py
- bluebottle/settings/testing.py
- bluebottle/slides/tests/test_api.py
- setup.py
And raise exception on naive datetime so we actually fix the issues.
> Upgrade DRF to 2.4

- bluebottle/bb_accounts/templates/bb_accounts/activation_email.html
- bluebottle/bb_accounts/templates/bb_accounts/activation_email.txt
Change blocktrans in welcome mail so it shows up in transifex again
> Change blocktrans in welcome mail.

- setup.py
This is from release/dll branch!
Master is ahead with Django 1.9 support.
> New Token auth version 0.2.30

- bluebottle/donations/admin.py
- bluebottle/donations/models.py
- bluebottle/donations/serializers.py
- bluebottle/payments/views.py
- bluebottle/payments_pledge/adapters.py
- bluebottle/payments_pledge/tests/test_adapter.py
- bluebottle/payments_pledge/tests/test_api.py
> Fix pledge while loging in in donation flow

- bluebottle/bb_organizations/models.py
- bluebottle/organizations/models.py
- bluebottle/organizations/tests/test_api.py
- bluebottle/payments/models.py
- bluebottle/payments/tests/test_models.py
- bluebottle/test/factory_models/payments.py
And clean up use of full_clean in models
> fix organization creation BB-7109

- bluebottle/payouts/admin.py
> Fix project link in admin payout list.

- bluebottle/bluebottle_drf2/serializers.py
> Fix scaling of profile images

- bluebottle/wallposts/admin.py
> Fix wallpost admin

- bluebottle/bb_tasks/tests/test_api.py
- bluebottle/bb_tasks/views.py
- bluebottle/tasks/models.py
Needs a thorough review before merging this to master. It might also be a good idea to merge to anew release branch first.
> Use utc in task date range and clean up code BB-7497

- setup.py
* Adds nameId to user data
* Does not create an empty user
> Upgrade token-auth.

- bluebottle/bb_payouts/models.py
- bluebottle/clients/utils.py
- bluebottle/settings/base.py
- bluebottle/utils/fields.py
- setup.py
+ Read currencies from tenant settings (lazily).
+ Expose currencies in config api.
BB-7633 #resolve
BB-7634 #resolve
> Lazy currency loading. Add currencies to cfg api.

- bluebottle/pages/models.py
> Fix deleting pages in admin

- bluebottle/projects/serializers.py
- bluebottle/projects/tests/test_api.py
- bluebottle/votes/models.py
- bluebottle/votes/serializers.py
- bluebottle/votes/tests/test_api.py
on an active project within the category
BB-7574 #resolve
> Besides checking if a user voted on a project, also check if the user

- bluebottle/utils/utils.py
BB-7830 #resolve
Plus some pep8 fixes.
> Fix for "extra" group permissions not loading on migrate

- bluebottle/bb_organizations/views.py
- bluebottle/organizations/tests/test_api.py
- bluebottle/organizations/views.py
> Fix for creating organization during project create

- bluebottle/homepage/tests/test_api.py
- bluebottle/statistics/statistics.py
- bluebottle/statistics/tests/test_unit.py
> Correctly calculate the donated total statistics

- bluebottle/projects/models.py
- bluebottle/projects/tests/test_api.py
with multiple currencies.
BB-7807 #resolve
> Sort on percentage needed instead of the amounts. Makes sorting work

- bluebottle/projects/models.py
- bluebottle/projects/tests/test_api.py
- bluebottle/settings/testing.py
> Take list of currencies from amount_asked

- bluebottle/votes/models.py
- bluebottle/votes/tests/test_api.py
already voted twice. (Because a category was added later).
> Make sure that we correctly check if a user already voted even when they

- setup.py
> Bump django-token-auth version to fix unicode urls in booking auth

- bluebottle/settings/base.py
> Disable thumbnail debugging by default. If needed you can always enable

- bluebottle/projects/serializers.py
- bluebottle/projects/tests/test_api.py
- setup.py
> escape story text in project to prevent XSS

- bluebottle/projects/serializers.py
> Send tasks in Manage Project api call

- bluebottle/analytics/__init__.py
- bluebottle/analytics/apps.py
- bluebottle/analytics/backends.py
- bluebottle/analytics/tests/test_models.py
- bluebottle/analytics/utils.py
- bluebottle/projects/models.py
- add location group name to project analytics
- fix importing of analytics signals
> Fix tests and add logging for failed influxdb writes  BB-7933

- bluebottle/analytics/signals.py
- bluebottle/analytics/tests/common.py
- bluebottle/analytics/tests/test_models.py
- bluebottle/analytics/tests/test_unit.py
- bluebottle/orders/models.py
- bluebottle/tasks/models.py
And snakecase the metric type rather than camelize.
> Update analytics fields to mirror exported static data BB-7933

- bluebottle/projects/templates/projects/mails/organization_project_complete.mail.html
- bluebottle/projects/templates/projects/mails/organization_project_complete.mail.txt
- bluebottle/projects/templates/projects/mails/project_complete.mail.html
- bluebottle/projects/templates/projects/mails/project_complete.mail.txt
- bluebottle/tasks/templates/tasks/mails/task_status_closed.mail.html
- bluebottle/tasks/templates/tasks/mails/task_status_closed.mail.txt
> Fix email templates for task flow.

- bluebottle/surveys/admin.py
- bluebottle/surveys/models.py
- bluebottle/surveys/tests/test_unit.py
- bluebottle/test/factory_models/surveys.py
> Make sure table-radio keeps oroiginal ordering

- bluebottle/surveys/admin.py
- bluebottle/surveys/models.py
This is the start of the admin cleanups. Malou added other issues in the ticket.
> Fix up survey admin

- bluebottle/settings/admin_dashboard.py
- bluebottle/surveys/admin.py
- bluebottle/surveys/models.py
> Admin improvements for surveys

- bluebottle/tasks/serializers.py
> Fix checking deadline if it is already set

- bluebottle/projects/mails.py
- bluebottle/projects/tests/test_mail.py
- bluebottle/tasks/taskmail.py
> Really do not send link if the project says not to celebrate

- bluebottle/analytics/signals.py
- bluebottle/analytics/tests/test_models.py
- bluebottle/projects/models.py
- bluebottle/tasks/models.py
- bluebottle/utils/managers.py
> Send signals on project/task bulk updates.

- bluebottle/analytics/backends.py
- bluebottle/analytics/signals.py
- bluebottle/analytics/tests/test_models.py
- bluebottle/orders/models.py
And include currency for order if available
BB-8143 #resolve
> Return order total as float

- bluebottle/analytics/tests/test_models.py
- bluebottle/wallposts/models.py
> Add analytics for wallpost reactions

- bluebottle/analytics/signals.py
- bluebottle/analytics/tests/test_api.py
- bluebottle/analytics/tests/test_models.py
- bluebottle/projects/models.py
- bluebottle/tasks/models.py
and add test for taskmember status changing to realized
BB-8164 BB-8115
> Translateable analytics tags/fields

- bluebottle/projects/serializers.py
> Add id to project budgetlines, so that we can treat them as ember

- bluebottle/projects/admin.py
> Make sure we don't divide by 0

- bluebottle/bb_follow/models.py
- bluebottle/geo/admin.py
> Fix follow unicode so admin don't hangs on wierd chars

- bluebottle/bb_accounts/tests/test_api.py
- bluebottle/settings/base.py
BB-8161 #resolve
BB-8160 #resolve
> Add security settings for CSRF cookies.

- bluebottle/analytics/tests/test_api.py
- bluebottle/analytics/tests/test_models.py
- bluebottle/members/models.py
> Add last_seen to member analytics

- bluebottle/accounting/admin.py
- bluebottle/payments/admin.py
- bluebottle/payments/templates/admin/payments/orderpayment/change_form.html
- bluebottle/payments_vitepay/adapters.py
For now disable the orderadmin from accounting...
> Add payment status check to admin

- bluebottle/bb_donations/tests/test_api.py
- bluebottle/journals/models.py
- bluebottle/journals/tests/test_models.py
- setup.py
Fix journals for donations.
BB-7914 #resolve
> Upgrade to django-money to current master.

- bluebottle/analytics/tests/test_models.py
- bluebottle/orders/models.py
> Correctly send currency in to influxdb

- bluebottle/payments_vitepay/tests/test_views.py
> Add tests for vitepay update endpoint

- bluebottle/donations/admin.py
> Add fundraiser to donation export

- bluebottle/bb_tasks/templates/task_member_applied.mail.html
- bluebottle/bb_tasks/templates/task_member_applied.mail.txt
- bluebottle/bb_tasks/templates/task_member_withdrew.mail.html
- bluebottle/bb_tasks/templates/task_member_withdrew.mail.txt
- bluebottle/tasks/taskmail.py
- bluebottle/tasks/tests/test_mails.py
Use the user's full name in the body
BB-8242 #resolve
BB-8140 #resolve
> Make sure that a mail is send when user withdraws from task.

- bluebottle/clients/tests/test_api.py
- bluebottle/payments/services.py
- bluebottle/payments_interswitch/tests/test_api.py
- bluebottle/payments_mock/settings.py
- bluebottle/payments_vitepay/tests/test_api.py
- bluebottle/projects/models.py
- bluebottle/settings/payments.py
- bluebottle/test/test_runner.py
- bluebottle/utils/fields.py
- bluebottle/utils/serializers.py
> Group currency settings in payment methods

- bluebottle/settings/base.py
> Add timestamp to logging verbose + simple

- bluebottle/projects/models.py
> Really set amount_extra currency to project currency.

- bluebottle/sepa/sepa.py
> Fix sepa exports not using Money objects.

- bluebottle/bb_payouts/models.py
> Make sure the organization fee is in the project currency.

- bluebottle/clients/templates/admin_tools/menu/menu.html
- bluebottle/clients/templates/rest_framework/base.html
> Make sure we use the django version of jquery everywhere.

- bluebottle/projects/management/commands/cron_status_realised.py
- bluebottle/projects/tests/test_management.py
> Correctly compare amount in cron status realised

- bluebottle/bb_accounts/views.py
- bluebottle/members/serializers.py
- bluebottle/urls/i18n_urls.py
reset form
And enable admin password reset again
BB-8154 #resolve
> Make it impossible to  check which users exist through the password

- bluebottle/settings/base.py
> Increase data upload size

- bluebottle/projects/admin.py
Reduntely add region filter to list_filter property. It fails if it's only added in get_list_filter
BB-8497 #resolve
> Add filter

- bluebottle/payouts/admin.py
- bluebottle/payouts/tests/test_admin.py
- bluebottle/payouts/tests/test_unit.py
- bluebottle/recurring_donations/tests/test_admin.py
- bluebottle/test/utils.py
- bluebottle/urls/core.py
> Show decimals for admin payout rules + test

- bluebottle/projects/admin.py
- bluebottle/projects/models.py
- Also change the widget to a list of checkboxes
BB-8507 #resolve
> Make sure currencies is not required in the admin.

- bluebottle/clients/tests/test_api.py
- bluebottle/clients/utils.py
> Expose minimum amounts per currency in config api

- bluebottle/payments/models.py
- bluebottle/payments/serializers.py
- bluebottle/payments/tests/test_models.py
- bluebottle/payments_docdata/tests/test_models.py
- bluebottle/payments_interswitch/adapters.py
- bluebottle/payments_interswitch/models.py
- bluebottle/payments_interswitch/tests/test_views.py
- bluebottle/payments_logger/tests/test_unittests.py
- bluebottle/payments_vitepay/tests/test_api.py
> include status description / code if order_payment response

- bluebottle/analytics/signals.py
- bluebottle/recurring_donations/admin.py
And avoid double negative when checking celery in analytics
> Check correct celery setting for monthly donations

- bluebottle/projects/serializers.py
- bluebottle/projects/tests/test_api.py
- bluebottle/utils/fields.py
> create generic safe field and use with project title

- bluebottle/geo/admin.py
- bluebottle/geo/tests/test_admin.py
> Add number of projects and link to projects to location admin

- .flake8
- bluebottle/cms/models.py
> Hide title/subtitle in results quote block

- bluebottle/analytics/backends.py
- bluebottle/analytics/exception.py
- bluebottle/analytics/tasks.py
- bluebottle/analytics/tests/test_unit.py
- bluebottle/settings/base.py
> Write analytics/influxdb json to disk

- bluebottle/clients/utils.py
> Overwrite US$ to $

- bluebottle/bluebottle_drf2/serializers.py
> Do not use watermark argument if no watermark is present.

- bluebottle/tasks/admin.py
> Add project location to taskmember export

- bluebottle/projects/models.py
- bluebottle/tasks/models.py
- bluebottle/tasks/signals.py
bulk changes.
BB-8850 #resolve
> Create phaselogs/statuslogs in signals so that they are also created on

- bluebottle/projects/models.py
- bluebottle/projects/tests/test_api.py
- bluebottle/projects/tests/test_management.py
dates to signals, so that it is triggered on bluk actions.
BB-8851 #resolve
> Move setting of 'campaign_started', 'date_submitted', 'campaign_ended'

- bluebottle/bluebottle_drf2/serializers.py
- bluebottle/cms/serializers.py
- bluebottle/cms/tests/test_api.py
- bluebottle/settings/base.py
- setup.py
This image is the result page header image, with the site logo overlayed.
BB-8837 #resolve
> Generate an image for sharing the result page.

- bluebottle/projects/admin.py
- bluebottle/settings/base.py
> Export amount extra. Both in projects export and general export.

- bluebottle/donations/admin.py
- bluebottle/fundraisers/admin.py
- bluebottle/geo/admin.py
- bluebottle/members/admin.py
- bluebottle/news/admin.py
- bluebottle/pages/admin.py
- bluebottle/payments/admin.py
- bluebottle/payments_docdata/admin.py
- bluebottle/payments_logger/admin.py
- bluebottle/payments_voucher/admin.py
- bluebottle/payouts/admin_utils.py
- bluebottle/projects/admin.py
- bluebottle/quotes/admin.py
- bluebottle/recurring_donations/admin.py
- bluebottle/slides/admin.py
- bluebottle/suggestions/admin.py
- bluebottle/surveys/admin.py
- bluebottle/tasks/admin.py
- bluebottle/wallposts/admin.py
creates cross site scripting possibilities.
> Do not use deprecated ALLOW_TAGS in admin classes. Especially if it

- bluebottle/payments_flutterwave/adapters.py
- bluebottle/payments_flutterwave/tests/test_adapters.py
- bluebottle/payments_interswitch/adapters.py
> Make it possible to do verve donation with unicode characters in your

- bluebottle/projects/tests/test_deadline.py
project finishes
BB-9043 #resolve
> Test that we actually set that payout status to needs_approval when a

- bluebottle/cms/admin.py
- bluebottle/cms/models.py
- bluebottle/statistics/models.py
- bluebottle/statistics/statistics.py
- bluebottle/statistics/tests/test_unit.py
BB-8834 #resolve
BB-8835 #resolve
BB-8836 #resolve
BB-8890 #resolve
> Add extra stats

- bluebottle/cms/serializers.py
- bluebottle/cms/tests/test_api.py
taht it is possible to display the most recent project
BB-8831 #resolve
> Order the projects in the results page map block on campaign ended, so

- bluebottle/analytics/tests/test_models.py
- bluebottle/tasks/models.py
> Return the hours since task realized when task member becomes realized

- bluebottle/bb_projects/models.py
- bluebottle/organizations/admin.py
- bluebottle/projects/admin.py
- bluebottle/settings/base.py
* Add relevant fields to the list
* Remove not relevant fields from the detail view
* Add related projects inline
* Make it possible to filter on project location and theme
* Make it possible to export as csv
* Add organization to project export
> Tweak the organization admin:

- bluebottle/analytics/management/commands/export_analytics_data.py
Reverts onepercentclub/bluebottle#2602
> Revert "fix importing of record by date updated"

- bluebottle/payouts_dorado/serializers.py
- bluebottle/payouts_dorado/tests/test_api.py
> Fix target-reached for payouts

- bluebottle/projects/admin.py
- bluebottle/projects/tests/test_admin.py
> Fixate status after payout

- bluebottle/payouts_dorado/adapters.py
- bluebottle/payouts_dorado/tests/test_adapter.py
- bluebottle/projects/models.py
- bluebottle/settings/testing.py
> Handle missing dorado settings

- bluebottle/settings/base.py
- bluebottle/tasks/models.py
- bluebottle/tasks/tests/test_mails.py
> Make it possible to configure the delay for reminder emails.

- bluebottle/projects/admin.py
- bluebottle/settings/base.py
> Add reviewer to projects export

- bluebottle/projects/serializers.py
that we can display the correct number of people needed in the project
create preview widget.
> Add people_needed and people_requested to ManageProjectSerializer, so

- bluebottle/common/templates/base.mail.html
> Make a little bit more room for the action button in the email

- bluebottle/tasks/models.py
> Remove parentheses from translateble string

- bluebottle/payouts_dorado/adapters.py
- bluebottle/payouts_dorado/serializers.py
- bluebottle/payouts_dorado/tests/test_adapter.py
- bluebottle/projects/admin.py
- bluebottle/projects/models.py
- bluebottle/projects/tests/test_admin.py
to the user about that validation error.
BB-9139 #resolve
> When a payout fails to create due to validation errors, show a message

- bluebottle/bb_tasks/tests/test_api.py
- bluebottle/payouts_dorado/adapters.py
- bluebottle/projects/admin.py
- bluebottle/projects/tests/test_admin.py
- bluebottle/tasks/serializers.py
connection or configuration errors.
BB-9327 #resolve
> Show proper errors to the user if a payout cannot be created, due to

- bluebottle/projects/admin.py
- bluebottle/statistics/statistics.py
* Show amount_exta for all projects (noet just finished ones)
* Show amount_extra in project admin list
> Show all amount extra for stats

- bluebottle/payouts_dorado/tests/test_api.py
- bluebottle/projects/admin.py
- bluebottle/projects/models.py
> Set payed out date

- bluebottle/organizations/serializers.py
- bluebottle/organizations/tests/test_api.py
- bluebottle/organizations/urls/api.py
- bluebottle/organizations/views.py
- added id for contacts in response
- added querysets to ContactList and ContactDetail because Django said
so
- fixed contact_list url
> Organization picker fixes

- bluebottle/organizations/admin.py
- bluebottle/organizations/models.py
- bluebottle/organizations/tests/test_admin.py
- bluebottle/organizations/tests/test_models.py
Redirect to master organization after merge in admin
BB-9518 #resolve
BB-9519 #resolve
> Merge contacts when merging organizations

- bluebottle/organizations/tests/test_api.py
- bluebottle/organizations/views.py
> Simplify the org search

- bluebottle/tasks/serializers.py
- bluebottle/tasks/signals.py
- remove check that prevent overwrite custom time_spent on task member object
> Add time_spent serializers

- bluebottle/bluebottle_drf2/pagination.py
> Make it possible to send a page_size parameter to all paged endpoints.

- bluebottle/donations/management/commands/export_donations.py
- bluebottle/payments_docdata/models.py
- bluebottle/payments_interswitch/models.py
- bluebottle/payments_mock/models.py
- bluebottle/payments_pledge/models.py
- bluebottle/payments_vitepay/models.py
- bluebottle/payments_voucher/models.py
> Add external transaction reference to order export

- bluebottle/organizations/serializers.py
- bluebottle/projects/serializers.py
- bluebottle/projects/tests/test_api.py
> Embed organization in project API endpoint

- bluebottle/settings/base.py
> Add some settings for task flow

- bluebottle/projects/models.py
- bluebottle/projects/tests/test_api.py
> Make it possible to filter project previews on task skill and date.

- bluebottle/tasks/serializers.py
- bluebottle/tasks/tests/test_api.py
> Allow task member without motivation + test

- bluebottle/tasks/serializers.py
- bluebottle/tasks/tests/test_api.py
This reverts commit 787841ea3f50f539c575c2550e12635dca8e1d04.
> Revert "Allow taskmember without motivation + test"

- bluebottle/tasks/signals.py
- bluebottle/tasks/tests/test_api.py
> Make sure we can set time_spent on task member

- bluebottle/bb_projects/views.py
- bluebottle/projects/serializers.py
- bluebottle/projects/tests/test_api.py
> Expose the list of skills related to a project in project list

- bluebottle/tasks/taskmail.py
- bluebottle/tasks/tests/test_mails.py
> Only send task member status mail when task member status has changed

- bluebottle/projects/tests/test_api.py
- bluebottle/tasks/taskmail.py
- bluebottle/tasks/templates/tasks/mails/deadline_changed.mail.html
- bluebottle/tasks/templates/tasks/mails/deadline_changed.mail.txt
- bluebottle/tasks/tests/test_mails.py
> Send an email to the taskmembers when the deadline of the project

- bluebottle/projects/models.py
- bluebottle/projects/tests/test_api.py
> Make it possible to filter on projects that have a task that can be done

- setup.py
BB-9659
https://github.com/onepercentclub/django-token-auth/commit/dd1b452bfb4023320559edb36b74f9c5ccdf7192
> Bump token-auth package

- bluebottle/tasks/models.py
- bluebottle/tasks/templates/tasks/mails/task_status_closed.mail.html
- bluebottle/tasks/templates/tasks/mails/task_status_closed.mail.txt
- bluebottle/tasks/tests/test_mails.py
- bluebottle/tasks/tests/test_models.py
> Revert removal of code that sets tasks without accepted members to

- bluebottle/projects/models.py
- bluebottle/projects/tests/test_api.py
> Make sure that we do not return duplicate projects

- bluebottle/tasks/admin.py
- bluebottle/tasks/models.py
> Add deadline to apply to detail admin and export

- bluebottle/auth/views.py
> Fix admin pwd reset

- bluebottle/bb_follow/models.py
- bluebottle/members/admin.py
- bluebottle/projects/admin.py
- bluebottle/projects/management/commands/cron_status_realised.py
- bluebottle/projects/tests/test_management.py
- bluebottle/tasks/models.py
> Only send task mails for active projects

- bluebottle/tasks/admin.py
- bluebottle/tasks/serializers.py
- bluebottle/tasks/tests/test_api.py
> Make resume is not required in API + test

- bluebottle/bb_tasks/templates/task_member_applied.mail.html
- bluebottle/bb_tasks/templates/task_member_applied.mail.txt
- bluebottle/tasks/tests/test_mails.py
> Only show motivation when it is present

- bluebottle/settings/base.py
- bluebottle/tasks/admin.py
- bluebottle/tasks/models.py
- Rename deadline to apply field in export
- Remove expertise based field in export
- Add filters in task admin on Location and Expertise
- Add date realised time stamp in CSV export
- Add link to upload cv in task members
BB-9830 #resolve
BB-9932 #resolve
BB-9933 #resolve
BB-9969 #resolve
BB-10029 #resolve
> Various backoffice fixes for task flow

- bluebottle/utils/views.py
> Make sure we set content-disposition for private files

- bluebottle/members/tests/test_admin.py
- bluebottle/projects/models.py
- bluebottle/votes/models.py
> Fix opening profile when vote/project has unicode characters

- bluebottle/utils/backends.py
- bluebottle/utils/tests/test_backends.py
> Document and test Anonymous Authentication Backend

- .travis.yml
- bluebottle/wallposts/admin.py
> Fix wallpost admin not including the polymorpic content_type and

- bluebottle/categories/admin.py
- bluebottle/categories/models.py
- Set the help text for input areas
- Reduce the size of the description text area
> fix category blocks help text

- bluebottle/auth/middleware.py
> Fix issue with creating category blocks in IE11

- bluebottle/homepage/models.py
- bluebottle/homepage/views.py
- bluebottle/utils/models.py
- bluebottle/utils/permissions.py
- bluebottle/utils/views.py
This needs a permission created for "homepage.api_read_homepage".
> Add basic read permission for homepage api

- bluebottle/utils/permissions.py
> User doesn't need to be in a group to be considered authenticated

- bluebottle/bb_projects/tests/test_api.py
- bluebottle/bb_projects/views.py
- bluebottle/bb_tasks/tests/test_api.py
- bluebottle/bb_tasks/views.py
> Filter my projects / tasks based on project role

- bluebottle/bb_projects/views.py
- bluebottle/members/models.py
- bluebottle/members/serializers.py
- bluebottle/projects/models.py
- bluebottle/projects/serializers.py
- bluebottle/tasks/migrations/0031_set_owner_permissions.py
- bluebottle/utils/permissions.py
- bluebottle/utils/serializers.py
- bluebottle/wallposts/models.py
- bluebottle/wallposts/views.py
Correctly filter project lists
Correctly calculate related OneOf permission
Add missing skills permission for authenticated users
Fix wallpost filtering and permissions
> Various fixes for partner permissions:

- bluebottle/bb_accounts/models.py
> add help text to partner organization select field

- bluebottle/settings/base.py
Locale - FR
Locale - NL
Locale - EN
> add djmoney to installed apps to fix incorrect formatting of money

- bluebottle/projects/serializers.py
> Make sure we send a full profile in project previews

- bluebottle/organizations/serializers.py
- bluebottle/organizations/tests/test_api.py
> Allow blank descriptions on organizations

- bluebottle/bb_orders/models.py
- bluebottle/orders/signals.py
- bluebottle/orders/tasks.py
- bluebottle/orders/tests/test_tasks.py
> Timeout new orders after 10 minutes, locked orders after 3 hours

- bluebottle/bb_accounts/tests/test_api.py
- bluebottle/members/serializers.py
- bluebottle/settings/base.py
Expose phonenumber in Mange and CurrentUser profile.
BB-10579 #resolve
> Expose a project contact method settings

- bluebottle/utils/utils.py
> Mark u, h6 and em as safe

- bluebottle/organizations/admin.py
- bluebottle/organizations/models.py
- bluebottle/utils/tests/test_unit.py
BB-10707 #resolve
BB-10708 #resolve
BB-10709 #resolve
BB-10710 #resolve
> Small tweaks to the partner organization admin

- .travis.yml
- bluebottle/projects/serializers.py
- bluebottle/projects/tests/test_permissions.py
- bluebottle/utils/tests/test_unit.py
> Fix donation permissions related to projects

- bluebottle/projects/signals.py
- bluebottle/projects/templates/projects/mails/project_role.mail.html
- bluebottle/projects/templates/projects/mails/project_role.mail.txt
- bluebottle/projects/tests/test_mail.py
- bluebottle/utils/tests/test_unit.py
- bluebottle/wallposts/tests/test_api.py
> Send an email to an user if he is assigned a project role

- bluebottle/payments/mails.py
- bluebottle/payments/signals.py
- bluebottle/payments/templates/payments/mails/order_payment_refund.mail.html
- bluebottle/payments/templates/payments/mails/order_payment_refund.mail.txt
- bluebottle/payments/tests/test_mails.py
> Send email when order payment is refunded

- bluebottle/bb_accounts/templates/bb_accounts/activation_email.html
- bluebottle/bb_accounts/templates/bb_accounts/activation_email.txt
- bluebottle/bb_accounts/templates/bb_accounts/activation_email_no_password.html
- bluebottle/bb_accounts/templates/bb_accounts/activation_email_no_password.txt
- bluebottle/bb_accounts/tests/test_api.py
- bluebottle/bb_accounts/utils.py
- bluebottle/common/templates/base.mail.html
- bluebottle/common/templates/base.mail.txt
- bluebottle/members/tests/test_admin.py
- bluebottle/test/properties/test/settings.py
> Update user created emails

- bluebottle/utils/models.py
- bluebottle/utils/monkey_patch_money_readonly_fields.py
Yes, this uses an ugly hack, but it is the same hack that django-money
will use in a future version.
BB-10954 #resolve
> Correctly display money fields in the admin

- bluebottle/pages/tests/test_api.py
- bluebottle/pages/views.py
> Fall back to default language if current requested language does not

- bluebottle/payments/models.py
- bluebottle/payments/tests/test_models.py
> Change default payment description. We are goodup now

- bluebottle/cms/management/commands/migrate_homepage.py
> Correctly import related homepage objects

- bluebottle/cms/serializers.py
> Add some fields to the serializers

- bluebottle/cms/models.py
> Fix preview templates. Add default preview template.

- bluebottle/clients/management/commands/create_site_links.py
BB-11244 #resolve
BB-11106 #resolve
> Add logos and other settings during links creation

- bluebottle/clients/management/commands/create_site_links.py
> Correctly import highlighted links

- bluebottle/bb_tasks/templates/task_member_accepted.mail.html
- bluebottle/bb_tasks/templates/task_member_accepted.mail.txt
- bluebottle/tasks/taskmail.py
- bluebottle/tasks/tests/test_mails.py
email.
Also fix randomly failing test.
BB-11342 #resolve
> Make sure we use the right sender when sending task member accepted

- bluebottle/cms/serializers.py
- bluebottle/cms/tests/test_api.py
- bluebottle/test/factory_models/cms.py
> Allow html in steps text.

- bluebottle/analytics/reports.py
- only show locations with data for the year
- correctly display months in the cumulative / totals section
- add execution time to logger
> reporting export tweaks

- bluebottle/projects/admin.py
- bluebottle/projects/tests/test_admin.py
> Add description to reward export

- bluebottle/analytics/management/commands/export_participation_metrics.py
- bluebottle/analytics/tests/test_commands.py
- remove survey's from metrics export
> Fix for metrics export when current month is January

- bluebottle/projects/permissions.py
- bluebottle/projects/tests/test_permissions.py
> Correctly determine related object permission for running projects

- bluebottle/donations/management/commands/export_donations.py
- bluebottle/tasks/serializers.py
- bluebottle/tasks/tests/test_api.py
> Validate that we only have unique task members

- bluebottle/statistics/statistics.py
- bluebottle/statistics/tests/test_unit.py
> Use order created date when summing donations in a period

- bluebottle/organizations/admin.py
- bluebottle/organizations/models.py
contact export
BB-11009 #resolve
> Add field to partner organization export. Add partner organization

- bluebottle/payments/templates/payments/mails/order_payment_refund.mail.html
- bluebottle/payments/templates/payments/mails/order_payment_refund.mail.txt
> Reufnd period should be 10 days

- bluebottle/bluebottle_drf2/serializers.py
- bluebottle/projects/serializers.py
- bluebottle/projects/tests/test_api.py
Rename default_description to default_story.
> Make it possible to send a url for image fields.

- bluebottle/bluebottle_drf2/serializers.py
> Fix url project images

- bluebottle/projects/admin.py
- bluebottle/projects/tests/test_admin.py
> Add place to project export.

- bluebottle/projects/models.py
- bluebottle/projects/tests/test_deadline.py
become realised, even when they have no tasks and no target amount.
BB-11828 #resolve
> Only check deadline for running projects. Submitted tasks should never

- bluebottle/analytics/views.py
- bluebottle/projects/admin.py
- bluebottle/projects/tests/test_admin.py
- bluebottle/redirects/actions.py
- bluebottle/utils/admin.py
- bluebottle/utils/views.py
Without quotes, comma will make chrome think we send 2 headers.
BB-11787 #resolve
> Make sure we quote the filename in content-disposition headers.

- bluebottle/cms/serializers.py
- bluebottle/cms/tests/test_api.py
- bluebottle/cms/views.py
> Make it possible to not set a date on reslts pages.

- bluebottle/cms/admin.py
- bluebottle/cms/content_plugins.py
> Make it possible to delete stats block from homepage

- bluebottle/cms/models.py
This will make sure it show again in the admin
BB-11863 #resolve
> Add SupprtersTotalBlockPlugin to results pages plugins.

- bluebottle/projects/serializers.py
and in project detail.
BB-12013 #resolve
> Make sure categories are serialized in the same way in project create

- bluebottle/cms/admin.py
- bluebottle/cms/content_plugins.py
> Fix content-link admin. Do not use the menu item link model, but the

- bluebottle/projects/admin.py
- bluebottle/projects/tests/test_admin.py
amount_needed in the admin
BB-12218 #resolve
> Make sure we take amount_extra into account when calculating

- bluebottle/donations/templates/donations/mails/confirmation.mail.txt
- bluebottle/donations/templates/donations/mails/donation.txt
- bluebottle/donations/templates/donations/mails/payment_details.html
- bluebottle/donations/templates/donations/mails/payment_details.txt
- bluebottle/donations/tests/test_mails.py
> Add recipient and organization to donation confirmation

- bluebottle/members/admin.py
> Add can_pledge to user permissions tab

- bluebottle/clients/tests/test_api.py
- bluebottle/clients/utils.py
correectly serialize to json, and 0 makes more sense.
> Make the default for minAmount 0 instead of infinity. Infinity does not

- bluebottle/bb_projects/views.py
- bluebottle/statistics/statistics.py
- bluebottle/statistics/tests/test_unit.py
> Make sure we only count projects that are actually realized.

- bluebottle/projects/admin.py
> Fix sharing checkboxes

- bluebottle/donations/admin.py
- bluebottle/members/admin.py
- bluebottle/orders/admin.py
- bluebottle/payments/admin.py
- bluebottle/utils/admin.py
* Speed up the calculation of totals in the admin. This makes the orders
and donations lists usefull again.
> Make it impossible to delete users, orders and donations

- bluebottle/projects/admin.py
- bluebottle/projects/models.py
Hopefully have less confusing about different inputs for place & country
> Rename locatio to map and make fields readonly

- bluebottle/bb_accounts/tests/test_api.py
- bluebottle/members/serializers.py
to facebook
BB-12516  #resolve
> Expose a property that makes it possible to see if the user is connected

- bluebottle/clients/context_processors.py
- bluebottle/payments/models.py
- bluebottle/payments/templates/admin/payments/orderpayment/change_form.html
> Add properties back to context processor. Fix refund button not being

- bluebottle/bluebottle_dashboard/templates/jet.dashboard/dashboard_tools.html
> Changing "initials"  to "In use"

- bluebottle/members/admin.py
> Group the pledge fields for members.

- bluebottle/projects/models.py
> Change description of "allow_anonymous_rewards" to "allow guests to

- bluebottle/projects/admin.py
- bluebottle/tasks/models.py
> Add "expertise based" filter" and allow sorting on donated percentage.

- bluebottle/wallposts/admin.py
- bluebottle/wallposts/tests/test_admin.py
textwallpost admin.
Small fix for vieww online in mediawallpost admin.
BB-12592 #resolve
> Make sure we correctly figure out a link to the related object in

- bluebottle/projects/admin.py
> Fix duplicate & project type switching

- bluebottle/bluebottle_dashboard/dashboard.py
> Add recent actions widget to admin.

- bluebottle/categories/admin.py
- bluebottle/categories/models.py
> Order category

- bluebottle/bb_accounts/templates/bb_accounts/activation_email_no_password.html
- bluebottle/bb_accounts/templates/bb_accounts/activation_email_no_password.txt
- bluebottle/bb_accounts/templates/bb_accounts/password_reset_email.html
- bluebottle/bb_accounts/templates/bb_accounts/password_reset_email.txt
- bluebottle/members/admin.py
- bluebottle/members/tests/test_admin.py
> Send email password reset link with front-end url

- bluebottle/cms/static/fluent_contents/admin/cp_plugins.js
> Small changes to cp_plugins.js to fix reoredering

- bluebottle/projects/models.py
- bluebottle/projects/tests/test_unit.py
> Update payout status also when the project is updated manually

- bluebottle/utils/monkey_patch_parler.py
> Add all languages to fallback languages

- bluebottle/bb_projects/models.py
- bluebottle/bb_projects/tests/test_api.py
- bluebottle/geo/models.py
- bluebottle/projects/admin.py
- bluebottle/tasks/admin.py
- bluebottle/tasks/models.py
- bluebottle/utils/admin.py
- bluebottle/utils/managers.py
- bluebottle/utils/models.py
- bluebottle/utils/views.py
- setup.py
fields, without filtering out untranslated models.
BB-12794 #resolve
> Make it possible to correctly order translated models on translated

- bluebottle/projects/models.py
> Fix help wording for Project bank details reviewed.

- bluebottle/members/admin.py
- bluebottle/members/tests/test_admin.py
> Add link in back-office that makes it possible to resend a welcome email

- bluebottle/payments/templates/payments/mails/order_payment_refund.mail.html
> Fix project link in refund email

- bluebottle/bb_projects/fixtures/project_data.json
- bluebottle/donations/donationmail.py
- bluebottle/donations/models.py
- bluebottle/donations/tests/test_signals.py
- bluebottle/orders/signals.py
- bluebottle/tasks/taskmail.py
- bluebottle/utils/context_managers.py
is successfull.
BB-12668 #resolve
> Make sure we only send emails and create wallposts once when a donation

- bluebottle/bb_orders/models.py
> Make it possible to transition an order from refunded to success.

- bluebottle/cms/tests/test_api.py
- bluebottle/cms/views.py
- bluebottle/pages/admin.py
- bluebottle/utils/managers.py
- bluebottle/utils/models.py
> Fix page publication time zone juggling

- bluebottle/bb_follow/models.py
- bluebottle/bb_follow/templates/bb_follow/mails/wallpost_mail.mail.html
- bluebottle/bb_follow/templates/bb_follow/mails/wallpost_mail.mail.txt
- bluebottle/bb_follow/tests/test_models.py
> Add an unsubscribe link to follow emails.

- bluebottle/projects/models.py
total amount in the frontend.
BB-12990 #resolve
> Refunded donations are not cancelled. They should not be counted in the

- bluebottle/settings/base.py
lot of taskmembers) can still be submitted.
BB-13231 #resolve
> Update DATA_UPLOAD_MAX_NUMBER_FIELDS so that large forms (tasks with a

- bluebottle/tasks/serializers.py
- bluebottle/tasks/tests/test_api.py
> Validate that tasks for projects with a duration are within the duration

- bluebottle/projects/admin.py
- bluebottle/projects/tests/test_admin.py
@danielkroon If you can test this it can we released as a small fix.
Relates to https://onepercentclub.atlassian.net/browse/BB-13088
> Add all reviewers to project filter

- bluebottle/bb_orders/models.py
- bluebottle/projects/tests/test_api.py
- bluebottle/projects/views.py
- bluebottle/test/factory_models/projects.py
> Show "Anonymous user" instead of an empty name in donation export view

- bluebottle/projects/admin.py
> Fix 500 error when reviewer name contains unicode.

- bluebottle/utils/middleware.py
> Correctly activate tenant translations in API requests

- bluebottle/tasks/taskmail.py
This reverts commit d2b02372ba740b4fa92b19c3bc72fa03515af55b.
> Revert "Tenporarily disable sending task mail reminders"

- bluebottle/bluebottle_dashboard/static/fluent_contents/admin/cp_plugins.js
> Correctly handle nested inline in placeholder editor.

- bluebottle/members/admin.py
- bluebottle/members/tests/test_admin.py
> Make it impossible to edit the email of users that have more groups then

- bluebottle/projects/admin.py
> Fix unicode handling of project status actions

- bluebottle/payments/views.py
- bluebottle/payments_docdata/adapters.py
Fix error handling for unicode in docdata errors.
BB-13441 #resolve
> Make sure we do not send long addresses to docdata.

- bluebottle/payouts/serializers.py
account, and create a new one, since it is not possible to update the
country.
> When updating the country of a stripe payout account, we remove the old

- bluebottle/payments_stripe/admin.py
- bluebottle/payouts/admin/plain.py
- bluebottle/payouts/admin/stripe.py
- bluebottle/payouts/models.py
- bluebottle/payouts/templates/admin/payouts/plainpayoutaccount/change_form.html
- bluebottle/payouts/templates/admin/payouts/stripepayoutaccount/change_form.html
- bluebottle/projects/admin.py
- bluebottle/projects/models.py
- bluebottle/settings/admin_dashboard.py
* Add project admin filter by bank details reviewed (funding platforms only)
* Add button to check status to stripe payout admin
* Add button to set plain payout to reviewed
> Make it easier to review payout accounts

- bluebottle/payouts/admin/__init__.py
- bluebottle/payouts/admin/plain.py
- bluebottle/payouts/admin/stripe.py
- bluebottle/payouts/admin/utils.py
- bluebottle/payouts/models.py
- Fix project links with accents
- Document link to plain payout
- Add project link to plain payout
> Make project link unicode

- bluebottle/organizations/views.py
- bluebottle/tasks/tests/test_api.py
- bluebottle/utils/views.py
Fixes https://onepercentclub.atlassian.net/browse/BB-13632
> Use filetransfers for private files

- bluebottle/bluebottle_dashboard/dashboard.py
- bluebottle/payouts/dashboard.py
- bluebottle/payouts/templates/dashboard/payout_accounts_needing_actions.html
- bluebottle/projects/admin.py
Also show errors in project amount tab when payout account does not
validate correctly.
> Add dashboard for payout accounts that need action.

- bluebottle/payouts/serializers.py
> Allow blank country on payout account

- bluebottle/bb_follow/templates/bb_follow/mails/wallpost_mail.mail.html
- bluebottle/bb_follow/templates/bb_follow/mails/wallpost_mail.mail.txt
- bluebottle/common/templates/base.mail.html
- bluebottle/common/templates/base.mail.txt
> Move Unsubscribe link to footer

- bluebottle/projects/serializers.py
- bluebottle/tasks/serializers.py
my-task serializers.
BB-13964 #resolve
> Make sure we also return the place of tasks in project serializers and

- bluebottle/payments_stripe/adapters.py
> Set payment-descriptor for stripe payments

- bluebottle/bb_projects/views.py
- bluebottle/geo/models.py
- bluebottle/projects/documents.py
- bluebottle/projects/tests/test_search.py
Fix switching of lat/long coordinates
BB-14036 #resolve
> Fix boosting on themes

- bluebottle/payouts/models.py
- bluebottle/payouts/tests/data/stripe_account_unverified.json
- bluebottle/payouts/tests/test_admin.py
> Make sure check_update busts cached_property

- bluebottle/payments_stripe/adapters.py
- bluebottle/payments_stripe/tests/test_adapters.py
- bluebottle/payments_stripe/tests/test_webhooks.py
- bluebottle/payments_stripe/views.py
> Correctly handle stripe disputes.

- bluebottle/payouts/admin/stripe.py
- bluebottle/payouts/tests/data/stripe_account_verified.json
- bluebottle/payouts/tests/test_admin.py
> Make sure Stripe account shows if there are diacritics in the name

- bluebottle/members/admin.py
- bluebottle/members/tests/test_admin.py
> Add subscribed field to member export

- bluebottle/projects/serializers.py
> Add deadline_to_apply to project manage task serializer

- bluebottle/projects/admin.py
- bluebottle/projects/tests/test_admin.py
> Make sure projects cannot go live with a deadline too far in to the

- bluebottle/activities/documents.py
- bluebottle/activities/filters.py
- bluebottle/initiatives/documents.py
- bluebottle/initiatives/filters.py
Since sorting tokenized fields does not work, we add a new field that is not tokenized, and sort on that.
> Fix sorting by title

- bluebottle/token_auth/auth/base.py
- bluebottle/token_auth/tests/test_base.py
Fields that start with `custom` map to custom user fields. If the field
does not exist, an error is logged, and field is skipped.
> Make it possible to add custom user fields during saml login

- bluebottle/activities/admin.py
> Change activity admin list order

- bluebottle/events/serializers.py
> Fix required fields of events.

- bluebottle/activities/transitions.py
> Show missing fields when transitioning activity

- bluebottle/initiatives/serializers.py
- bluebottle/initiatives/tests/test_api.py
Reef: https://github.com/onepercentclub/reef/pull/5340
Ticket: https://onepercentclub.atlassian.net/browse/BB-14512
> Check for unique initiative title uniqueness

- bluebottle/events/models.py
- bluebottle/events/tests/test_models.py
> Do not mark the event as full if the capacity is not set

- bluebottle/activities/permissions.py
- bluebottle/events/tests/test_api.py
Modifying the permissions for activity manager to allow him/her creation of events
> Modifying the permissions for activity manager

- bluebottle/initiatives/documents.py
- bluebottle/initiatives/filters.py
- bluebottle/initiatives/serializers.py
- bluebottle/initiatives/tests/factories.py
- bluebottle/initiatives/tests/test_api.py
- bluebottle/initiatives/views.py
- bluebottle/utils/filters.py
> Also return activity_manager when filtering on owner

- bluebottle/funding/models.py
- bluebottle/funding/tests/test_models.py
related rewards and budget-lines.
> If the currency of a project changes, also change the currency of

- bluebottle/assignments/views.py
- bluebottle/initiatives/admin.py
> Either show office locations, or place in initiative admin, but not

- bluebottle/initiatives/serializers.py
> fixed new image sizes

- bluebottle/geo/serializers.py
- bluebottle/initiatives/models.py
- bluebottle/initiatives/serializers.py
- bluebottle/initiatives/urls/api.py
- bluebottle/initiatives/views.py
- bluebottle/projects/migrations/0091_project_to_initiatives.py
This will adds a new serializer for initiative items for the homepage map
Minified the request and also added caching so it should be waaaaaay faster.
> Initiatives map items for homepage

- bluebottle/organizations/serializers.py
- bluebottle/organizations/views.py
- bluebottle/utils/permissions.py
> Make organization read-only if the user is not the owner.

- bluebottle/bluebottle_drf2/renderers.py
> Make sure we also return a meta count for normal resource related

- bluebottle/bb_tasks/templates/task_member_rejected.mail.txt
- bluebottle/events/messages.py
- bluebottle/events/models.py
- bluebottle/events/tasks.py
- bluebottle/events/templates/mails/messages/participant_application.html
- bluebottle/events/templates/mails/messages/participant_application.txt
- bluebottle/events/templates/mails/messages/participant_rejected.html
- bluebottle/events/templates/mails/messages/participant_rejected.txt
- bluebottle/events/tests/test_api.py
- bluebottle/events/tests/test_tasks.py
- bluebottle/events/tests/test_transitions.py
- bluebottle/events/transitions.py
- When applying
- When rejected
BB-15447 #resolve
BB-15448 #resolve
> Add participant mails:

- bluebottle/cms/models.py
- bluebottle/statistics/statistics.py
> Fix some stats. Add new *_online status for all activities.

- bluebottle/activities/transitions.py
- bluebottle/initiatives/transitions.py
the review status of an initiative.
BB-15571 #resolve
> Fix how transitioning the review_status of activities when we transition

- bluebottle/activities/transitions.py
also set the status to `closed`
BB-15564 #resolve
> Make sure that when an activity is gets the review status `closed`, we

- bluebottle/activities/admin.py
- bluebottle/events/admin.py
BB-15607 #resolve
https://onepercentclub.atlassian.net/browse/BB-15607
> Show search field in activities admin. Fix filters for event admin

- bluebottle/tasks/migrations/0042_migrate_tasks_to_activities.py
> Also migrate task locations.

- bluebottle/projects/migrations/0091_project_to_initiatives.py
> Mirgate bank-accounts to pledge payout accounts if no matching currency

- bluebottle/funding/admin.py
> Add status filter to payout admin.

- bluebottle/funding/serializers.py
- bluebottle/funding/transitions.py
- bluebottle/funding/urls/api.py
- bluebottle/funding/views.py
> Fix creation and transitioning of payouts.

- bluebottle/activities/tests/test_api.py
- bluebottle/events/models.py
- bluebottle/events/tests/test_models.py
Check capacity when deleting participants
Check capacity when changing event.
BB-15675 #resolve
> Save event when reopening.

- bluebottle/funding/transitions.py
- bluebottle/funding_stripe/tests/test_webhooks.py
- bluebottle/funding_stripe/transitions.py
- bluebottle/funding_stripe/views.py
This will mark the payment as `pending` and the donation as `succeeded`.
> Add listener voor `charge.pending` events.

- bluebottle/utils/admin.py
Also fixes the typo in the permission.
> Check the right permission for model admin

- bluebottle/activities/admin.py
- bluebottle/funding/dashboard.py
- bluebottle/funding/templates/dashboard/bank_account_lists.html
- bluebottle/funding/transitions.py
- bluebottle/funding_flutterwave/admin.py
- bluebottle/funding_lipisha/admin.py
- bluebottle/funding_pledge/admin.py
- bluebottle/funding_stripe/admin.py
- bluebottle/funding_vitepay/admin.py
> Improve bank account list + search in admin

- bluebottle/activities/filters.py
- bluebottle/funding/tests/test_api.py
- bluebottle/initiatives/filters.py
- bluebottle/initiatives/tests/test_api.py
- bluebottle/utils/filters.py
> Add default sort field to initiative list api endpoint

- scripts/create_pledge_payments.py
> Add script that create pledge payments that were skipped by the

- bluebottle/initiatives/models.py
- bluebottle/organizations/admin.py
> Show related initiatives instead of related projects in initiative

- bluebottle/activities/documents.py
- bluebottle/activities/tests/test_api.py
- bluebottle/assignments/documents.py
- bluebottle/events/documents.py
- bluebottle/initiatives/models.py
This is easier then deleting the location in the save method, since we
do not want the location to disappear immediately.
BB-15764 #resolve
> Do not index the location of activities that have `is_online=True`.

- bluebottle/initiatives/serializers.py
- bluebottle/initiatives/tests/test_api.py
- bluebottle/initiatives/views.py
- Use list ipv full serializer
- Prefetch related objects
BB-16005 #resolve
> Optimize initiative list endpoint

- bluebottle/activities/tests/test_api.py
- bluebottle/files/serializers.py
- bluebottle/initiatives/tests/test_api.py
update immediately.
BB-15972 #resolve
> Add cache-bust param to file links. This will makes sure that images

- bluebottle/activities/admin.py
- bluebottle/activities/migrations/0013_auto_20191120_0920.py
- bluebottle/activities/templates/admin/activity-stats.html
- bluebottle/assignments/models.py
- bluebottle/funding/models.py
- bluebottle/initiatives/models.py
- bluebottle/initiatives/serializers.py
- bluebottle/initiatives/tests/test_api.py
This will make it way easier to show stats on succeeded initiatives.
BB-15896 #resolve
> Add stats to the meta of an initiative detail representation.

- bluebottle/notifications/models.py
> Add share on yammer options to notification settings

- bluebottle/activities/filters.py
- bluebottle/activities/serializers.py
- bluebottle/activities/utils.py
more correct when filling in a search term.
- Return less fields in activity list. This speeds things up greatly.
> Make popularity filter stronger when searching. This makes the ordering

- bluebottle/activities/serializers.py
- bluebottle/activities/tests/test_api.py
- bluebottle/activities/urls/api.py
- bluebottle/activities/utils.py
- bluebottle/activities/views.py
Only returns contributions of the current user. Returns all
contributions without pagination.
> Add my controbutions end point.

- bluebottle/funding/admin.py
- bluebottle/funding/models.py
- bluebottle/funding/tests/test_models.py
- bluebottle/funding/transitions.py
- bluebottle/funding_stripe/tests/factories.py
- bluebottle/funding_stripe/tests/test_webhooks.py
Fix for https://onepercentclub.atlassian.net/browse/BB-16058
> Fix hoe we generate payouts

- bluebottle/funding_stripe/views.py
> Also return a nice error when the stripe error has no param.

- bluebottle/funding/admin.py
- bluebottle/funding/filters.py
- bluebottle/funding/tests/test_admin.py
> Add pledged filter to donation admin

- bluebottle/assignments/admin.py
> Make sure you can add applicant from assignment admin

- bluebottle/activities/utils.py
We need this to show attendees count in activity search
> Add stats to activity list serializer

- bluebottle/funding/tests/test_transitions.py
- bluebottle/funding/transitions.py
> Set deadline on midnight for funding with duration

- bluebottle/funding/templates/mails/messages/donation_success_donor.html
- bluebottle/funding/templates/mails/messages/donation_success_donor.txt
- bluebottle/funding/templates/mails/messages/donation_success_owner.html
- bluebottle/funding/templates/mails/messages/donation_success_owner.txt
- bluebottle/funding/templates/mails/messages/partials/donation_receipt.html
- bluebottle/funding/templates/mails/messages/partials/donation_receipt.txt
- bluebottle/funding/tests/test_transitions.py
- bluebottle/utils/email_backend.py
> Show donation amount in initiator mail

- bluebottle/funding/admin.py
- bluebottle/funding/tests/test_admin.py
Make sure users can only select rewards that belong to the funding.
BB-16015 #resolve
> Make the reward of a donation editable in the admin.

- bluebottle/activities/serializers.py
- bluebottle/activities/tests/test_api.py
- bluebottle/activities/utils.py
- bluebottle/activities/views.py
- bluebottle/assignments/serializers.py
- bluebottle/events/serializers.py
- bluebottle/funding/serializers.py
Correctly set `prefetch_related`.
Only include a tiny activity.
> Optimize the contributions endpoint.

- bluebottle/organizations/serializers.py
> Add logo to organisation serializer

- bluebottle/initiatives/views.py
> Use full initiative serializer when browsing my initiatives

- bluebottle/categories/admin.py
> Show initiatives instead of project in category admin

- bluebottle/funding/admin.py
> Make sure to use the right numbers for donated total / percentage

- bluebottle/funding_stripe/models.py
- bluebottle/funding_stripe/tests/test_api.py
- bluebottle/funding_stripe/tests/test_models.py
> Make sure tenants with short names can create Stripe accounts

- bluebottle/events/models.py
- bluebottle/events/serializers.py
- bluebottle/events/tests/test_api.py
- bluebottle/events/urls/api.py
- bluebottle/events/views.py
- bluebottle/test/factory_models/geo.py
- setup.py
calendar.
- Add link to google calendar
- Add link to microsoft outlook
- Add link to ical download
- Add view that lets the user download an Ical file
BB-16087 #resolve
BB-16089 #resolve
> Add links to event resource that allow users to add the event to their

- bluebottle/pages/models.py
- bluebottle/settings/base.py
> Fix file permissions after uploading larger files to CMS page

- bluebottle/events/transitions.py
> We should not check can_open when transitioning to full

- bluebottle/assignments/tests/test_transitions.py
- bluebottle/assignments/transitions.py
> Also succeed applied assignment applicants

- bluebottle/events/models.py
- bluebottle/events/tests/test_api.py
> Fix unicode troubles in calendar links

- bluebottle/events/models.py
- bluebottle/events/tests/test_api.py
> Fix unicode troubles in calendar links (#3959)

- bluebottle/assignments/templates/mails/messages/assignment_date_changed.html
- bluebottle/assignments/templates/mails/messages/assignment_date_changed.txt
- bluebottle/events/templates/mails/messages/event_date_changed.html
- bluebottle/events/templates/mails/messages/event_date_changed.txt
- bluebottle/events/templates/mails/messages/event_reminder.html
- bluebottle/events/templates/mails/messages/event_reminder.txt
> goto > go to

- bluebottle/events/models.py
- bluebottle/events/tests/test_api.py
- bluebottle/events/views.py
> Make sure to remove html tags from event descriptions

- bluebottle/settings/base.py
> Add more fields to the export. Make it possible to export 3 years.

- bluebottle/bb_accounts/views.py
- bluebottle/members/tests/test_api.py
> Make sure the signup token can only be used once.

- bluebottle/notifications/admin.py
> Fix creating objects in notification admin views

- bluebottle/funding/admin.py
- bluebottle/funding/tests/test_api.py
- bluebottle/funding/transitions.py
> Start following funding activity when doing a succesfull donation

- bluebottle/funding_stripe/tests/test_transitions.py
- bluebottle/funding_stripe/transitions.py
> Fix and test refunding of stripe payment intents

- bluebottle/initiatives/documents.py
- bluebottle/initiatives/filters.py
- bluebottle/initiatives/tests/test_api.py
> Also include activity owners when filtering initiatives on owner.

- bluebottle/funding/admin.py
> Show 0% correctly

- bluebottle/funding/models.py
- bluebottle/funding/tests/test_models.py
> Only validate deadline is in the future when status in open or

- bluebottle/notifications/messages.py
Instead temporarily override it.
BB-16503 #resolve
> Do not set the language when creating a message.

- bluebottle/assignments/templates/mails/messages/assignment_date_changed.html
- bluebottle/events/templates/mails/messages/event_date_changed.html
- bluebottle/events/templates/mails/messages/event_succeeded_owner.html
- bluebottle/funding/templates/mails/messages/funding_realised_owner.html
> Do not add the protocol and host twice.

- bluebottle/events/serializers.py
- bluebottle/events/tests/test_api.py
- bluebottle/events/views.py
- bluebottle/utils/views.py
> Make event ical view a private file view, and return a signed url in the

- bluebottle/funding/admin.py
> Make it possible to edit the limit on rewards in the back-office

- bluebottle/funding/tests/test_api.py
- bluebottle/funding/views.py
> When exporting funding donations, do not include the organizer

- bluebottle/events/models.py
- bluebottle/events/tests/test_api.py
> Make sure we unescape html entities when creating calendar links

- bluebottle/funding/admin.py
Adds the owner column
https://onepercentclub.atlassian.net/browse/BB-16568
> adds owner to payout list in the admin

- bluebottle/follow/tests/factories.py
- bluebottle/initiatives/messages.py
- bluebottle/initiatives/models.py
- bluebottle/initiatives/tests/test_wallposts.py
a wallpost is posted on an initiative
BB-16522 #resolve
> Send a message to all followers of all approved activities when

- bluebottle/funding/templates/mails/messages/funding_realised_owner.html
- bluebottle/funding/templates/mails/messages/funding_realised_owner.txt
- bluebottle/funding/tests/test_transitions.py
> Fix url in funding success mail

- bluebottle/events/messages.py
- bluebottle/events/tests/test_models.py
> Do not send event organizer date changed / reminder emails

- bluebottle/exports/tests/test_export.py
- bluebottle/settings/base.py
> Add new date fields to export

- bluebottle/notifications/messages.py
- bluebottle/utils/translation.py
> Fix overriding translations

- bluebottle/assignments/messages.py
- bluebottle/assignments/templates/mails/messages/assignment_date_changed.html
- bluebottle/assignments/templates/mails/messages/assignment_date_changed.txt
- bluebottle/assignments/tests/test_models.py
- bluebottle/assignments/tests/test_tasks.py
the correct date in the email.
BB-16661 #resolve
> Make sure that accepted members also get date changed emails, include

- bluebottle/activities/models.py
- bluebottle/funding/models.py
- bluebottle/funding_lipisha/models.py
- bluebottle/funding_vitepay/models.py
- bluebottle/geo/models.py
- bluebottle/initiatives/models.py
BB-16797 #resolve
No weaknesses have been found, but makes sense to restrict using `format_html` to the places where we expect html.
> Replace some format_html's

- bluebottle/assignments/tests/factories.py
- bluebottle/geo/tests/test_api.py
- bluebottle/geo/views.py
> Use initiative, event and assignment countries to calculate used

- bluebottle/bb_accounts/views.py
- bluebottle/members/tests/test_api.py
> Send welcome mail on closed email platforms + test

- bluebottle/assignments/filters.py
- bluebottle/assignments/serializers.py
- bluebottle/assignments/tests/test_api.py
> Fix applicant lists in API

- bluebottle/assignments/tests/test_models.py
- bluebottle/bb_accounts/permissions.py
- bluebottle/bb_accounts/tests/test_api.py
- bluebottle/bb_accounts/views.py
- bluebottle/funding/serializers.py
- bluebottle/funding/tests/test_api.py
- bluebottle/funding_pledge/tests/test_api.py
- bluebottle/funding_stripe/models.py
- bluebottle/funding_stripe/tests/test_api.py
- bluebottle/utils/views.py
> Fix related permissions on non-create api calls

- bluebottle/members/admin.py
- bluebottle/members/forms.py
- bluebottle/members/templates/admin/members/login_as.html
- bluebottle/members/templates/admin/members/password_reset.html
- bluebottle/members/templates/admin/members/resend_welcome_mail.html
- bluebottle/members/tests/test_admin.py
- Send Reset password mail
- Login as
- Resend welcome mail
If applicable
> In member admin, add confirmation page to:

- bluebottle/bb_accounts/tests/test_api.py
- bluebottle/bb_accounts/views.py
> Block signup on closed platforms

- bluebottle/token_auth/auth/saml.py
- bluebottle/token_auth/tests/test_saml.py
Store the SAML request id in the session. When authenticating, make sure
to check the request id against the id in the session.
BB-16735 #resolve
If applicable
> Prevent SAML session reuse.

- bluebottle/files/tests/test_api.py
- bluebottle/files/views.py
> Check uploaded images against allowed mime types.

- bluebottle/token_auth/auth/saml.py
- bluebottle/token_auth/tests/test_saml.py
> Make sure it is impossible to repeat saml login requests

- bluebottle/auth/views.py
> Fix social login by passing in request

- bluebottle/funding_stripe/models.py
If applicable
- [ x] Added translatable strings to `server-deployment`
- [x ] Added translations to `sever-deployment`
> Set more statement descriptors

- bluebottle/funding/effects.py
- bluebottle/funding/states.py
- bluebottle/funding/tests/test_states.py
- bluebottle/funding_flutterwave/models.py
- bluebottle/funding_flutterwave/states.py
- bluebottle/funding_lipisha/models.py
- bluebottle/funding_lipisha/states.py
- bluebottle/funding_pledge/states.py
- bluebottle/funding_stripe/effects.py
- bluebottle/funding_stripe/models.py
- bluebottle/funding_stripe/states.py
- bluebottle/funding_stripe/tests/test_webhooks.py
- bluebottle/funding_stripe/views.py
- bluebottle/funding_vitepay/models.py
- bluebottle/funding_vitepay/states.py
> Fix stripe payments and fsm for all psps

- bluebottle/settings/base.py
> Add scim to lockdown url exceptions

- bluebottle/events/effects.py
- bluebottle/events/models.py
- bluebottle/events/states.py
- bluebottle/events/triggers.py
> Restructure events

- bluebottle/funding/templates/mails/messages/funding_closed.html
- bluebottle/funding/templates/mails/messages/funding_closed.txt
- bluebottle/funding/templates/mails/messages/funding_partially_funded.html
- bluebottle/funding/templates/mails/messages/funding_partially_funded.txt
- bluebottle/funding/templates/mails/messages/funding_realised_owner.html
- bluebottle/funding/tests/test_transitions.py
BB-16909 #resolve
If applicable
> Correctly render the title in all funding end messages.

- bluebottle/funding/admin.py
- bluebottle/funding/effects.py
- bluebottle/funding/states.py
- bluebottle/funding/tests/test_api.py
- bluebottle/funding/views.py
> Fix Payout states

- bluebottle/funding_stripe/models.py
- bluebottle/funding_stripe/tests/test_api.py
BB-16757 #resolve
If applicable
> Show errors when documents are somehow rejected.

- bluebottle/cms/serializers.py
BB-16877 #resolve
If applicable
> Do not show closed (or deleted / draft) activities on the homepage

- bluebottle/assignments/tests/test_transitions.py
- bluebottle/assignments/transitions.py
the assignment
BB-16964 #resolve
> Make sure that succeeding applicants works even if no duration is set on

- bluebottle/members/admin.py
> Allow users to be deleted if they don't have contributions

- bluebottle/assignments/tests/test_api.py
- bluebottle/files/tests/files/index.php
- bluebottle/files/views.py
- bluebottle/settings/base.py
> Limit private files upload types BB-16969

- bluebottle/cms/migrations/0060_auto_20200717_1037.py
> Fix stats migrations

- bluebottle/impact/admin.py
> Autopopulate slug

- bluebottle/impact/models.py
- bluebottle/statistics/admin.py
> Make impact stats conditional and some translatables

- bluebottle/assignments/admin.py
- bluebottle/assignments/templates/mails/messages/assignment_completed.html
- bluebottle/assignments/templates/mails/messages/assignment_completed.txt
- bluebottle/events/templates/mails/messages/event_succeeded_owner.html
- bluebottle/events/templates/mails/messages/event_succeeded_owner.txt
- bluebottle/funding/templates/mails/messages/funding_realised_owner.html
- bluebottle/funding/templates/mails/messages/funding_realised_owner.txt
> Add impact cta to succeeded emails

- bluebottle/impact/admin.py
> Add unit to inline impact goals in activity admin

- bluebottle/activities/models.py
- bluebottle/events/tests/test_models.py
- bluebottle/initiatives/models.py
- bluebottle/initiatives/tests/test_model.py
> Sanitize fields before saving, to prevent XSS attacks

- bluebottle/bluebottle_drf2/serializers.py
> Disable file uploads by POSTing an url

- bluebottle/utils/models.py
- bluebottle/utils/monkey_patch_jet.py
> CSRF protect jet's widget views.

- bluebottle/exports/tasks.py
- bluebottle/exports/templates/exportdb/base.html
- bluebottle/exports/tests/test_api.py
- bluebottle/exports/urls.py
- bluebottle/exports/views.py
- bluebottle/settings/base.py
> Make sure we protect metric exports

- bluebottle/cms/serializers.py
- bluebottle/files/models.py
- bluebottle/pages/models.py
- bluebottle/utils/validators.py
> Restrict mimetypes of files in admin

- bluebottle/initiatives/tests/test_api.py
- bluebottle/initiatives/urls/api.py
- bluebottle/initiatives/views.py
> Add a json-api endpoint for themes

- bluebottle/assignments/states.py
- bluebottle/events/templates/admin/reset_time_spent_effect.html
- bluebottle/events/templates/admin/set_time_spent_effect.html
- bluebottle/fsm/templates/admin/transition_effect.html
> Fix some assignment transitions

- bluebottle/funding_lipisha/utils.py
> Make sure we use donor name for mpesa wp and thank you sms

- bluebottle/activities/states.py
- bluebottle/fsm/effects.py
- bluebottle/fsm/periodic_tasks.py
- bluebottle/fsm/state.py
- bluebottle/funding/effects.py
- bluebottle/funding/models.py
- bluebottle/funding/states.py
- bluebottle/funding/templates/admin/funding/payment/change_form.html
- bluebottle/funding/tests/test_admin.py
- bluebottle/funding/tests/test_states.py
- bluebottle/funding/tests/test_transitions.py
- bluebottle/funding_flutterwave/states.py
- bluebottle/funding_lipisha/states.py
- bluebottle/funding_pledge/states.py
- bluebottle/funding_stripe/effects.py
- bluebottle/funding_stripe/models.py
- bluebottle/funding_stripe/states.py
- bluebottle/funding_stripe/tests/factories.py
- bluebottle/funding_stripe/tests/test_states.py
- bluebottle/funding_telesom/states.py
- bluebottle/funding_vitepay/states.py
- bluebottle/notifications/effects.py
> Hotfix/ more funding st

- bluebottle/activities/admin.py
- bluebottle/fsm/admin.py
- bluebottle/initiatives/admin.py
> Fix polymorphic admins. Fix initiative admin

- bluebottle/activities/states.py
- bluebottle/assignments/states.py
- bluebottle/assignments/tests/test_api.py
- bluebottle/funding/states.py
- bluebottle/initiatives/states.py
- bluebottle/initiatives/tests/test_states.py
> Fix auto submitting and approving activities

- bluebottle/activities/admin.py
- bluebottle/assignments/admin.py
- bluebottle/events/admin.py
> Use statename in inline applicants

- bluebottle/assignments/tests/test_models.py
- bluebottle/funding_lipisha/tests/test_api.py
- bluebottle/funding_lipisha/utils.py
> Fix Mpesa push payments

- bluebottle/events/states.py
- bluebottle/initiatives/states.py
> Some small content fixes for tooltips

- bluebottle/events/validators.py
> Fix validation string

- bluebottle/initiatives/views.py
- bluebottle/projects/admin.py
Also fix admin showing links to projects instead of initiatives
If applicable
> Fix theme list translations

- bluebottle/assignments/serializers.py
- bluebottle/assignments/tests/test_api.py
- bluebottle/assignments/urls/api.py
- bluebottle/assignments/views.py
> Add json-api endpoint for skills

- bluebottle/exports/tests/test_export.py
- bluebottle/settings/base.py
- Add inititive title
- Add activity status
- Add activity date / deadline
- Change name of created field
If applicable
> Add some fields to contribution exports

- bluebottle/assignments/admin.py
- bluebottle/events/admin.py
- bluebottle/fsm/triggers.py
- bluebottle/funding/admin.py
> Do not fail when saving models without state machines

- bluebottle/activities/models.py
> Rename organizer to activity owner

- bluebottle/activities/admin.py
> Only show "steps to complete" when still editing / reviewing activities

- bluebottle/geo/tests/test_api.py
- bluebottle/geo/urls/api.py
- bluebottle/geo/views.py
> Fix used countries

- bluebottle/geo/tests/test_api.py
- bluebottle/geo/views.py
> Make sure we corretly filter on initiatives when finding used countries

- bluebottle/funding/states.py
- bluebottle/funding/tests/test_states.py
BB-17382  #resolve
If applicable
> Make sure we don't crash on funding without target

- bluebottle/funding/admin.py
- bluebottle/funding_stripe/admin.py
> Fix link if no funding is found

- bluebottle/activities/filters.py
> Also filter activities on cancelled

- bluebottle/looker/templates/dashboard/embed.html
> Smaller Looker iframe

- bluebottle/fsm/forms.py
> Make sure Initiative can save

- bluebottle/activities/tests/test_api.py
- bluebottle/exports/tests/test_export.py
- bluebottle/initiatives/tests/test_api.py
> Reduce te size/duration of some tests

- bluebottle/funding/states.py
> Allow pending -> verified on payout accounts

- bluebottle/funding/serializers.py
- bluebottle/funding/tests/factories.py
- bluebottle/funding/tests/test_api.py
- bluebottle/funding/urls/api.py
- bluebottle/funding/views.py
> Remove fundraisers from API

- bluebottle/assignments/templates/mails/messages/assignment_reminder_deadline.html
- bluebottle/assignments/templates/mails/messages/assignment_reminder_deadline.txt
- bluebottle/assignments/templates/mails/messages/assignment_reminder_on_date.html
- bluebottle/assignments/templates/mails/messages/assignment_reminder_on_date.txt
- bluebottle/events/templates/mails/messages/event_reminder.html
- bluebottle/events/templates/mails/messages/event_reminder.txt
> changed-copy

- bluebottle/assignments/tests/test_models.py
- bluebottle/events/models.py
- bluebottle/events/templates/mails/messages/event_date_changed.html
- bluebottle/events/templates/mails/messages/event_date_changed.txt
- bluebottle/events/tests/test_models.py
> Display local time and timezone in date changed mails

- bluebottle/assignments/tests/test_api.py
- bluebottle/assignments/urls/api.py
- bluebottle/assignments/views.py
- bluebottle/initiatives/tests/test_api.py
- bluebottle/initiatives/urls/api.py
- bluebottle/initiatives/views.py
> Add theme detail api

- bluebottle/exports/tests/test_export.py
- bluebottle/geo/tests/test_admin.py
- bluebottle/members/admin.py
- bluebottle/members/models.py
> Fix unicode and improve token auth admin

- bluebottle/exports/tests/test_export.py
> Fix Parblue test again :-)

- bluebottle/members/serializers.py
> For now add project_manage_list to user permissions

- bluebottle/assignments/templates/mails/messages/assignment_reminder_deadline.html
- bluebottle/assignments/templates/mails/messages/assignment_reminder_deadline.txt
- bluebottle/assignments/templates/mails/messages/assignment_reminder_on_date.html
- bluebottle/assignments/templates/mails/messages/assignment_reminder_on_date.txt
> Added copy for when not accepted

- bluebottle/settings/base.py
> Fix logging formatting

- bluebottle/initiatives/serializers.py
- bluebottle/initiatives/tests/test_api.py
> Include activity image in initiative detail serializer.

- bluebottle/token_auth/auth/booking.py
- bluebottle/token_auth/tests/test_booking.py
Do not forget to remove the b'' from the booking settings.
> Fix encoding of keys for booking auth

- bluebottle/funding_flutterwave/tests/test_webhooks.py
- bluebottle/funding_flutterwave/views.py
> Make Flw view Python 3 compatible

- bluebottle/funding/admin.py
- bluebottle/funding/states.py
- bluebottle/funding/templates/admin/delete_uploaded_document_effect.html
- bluebottle/funding_flutterwave/admin.py
- bluebottle/funding_lipisha/admin.py
- bluebottle/funding_pledge/admin.py
- bluebottle/funding_telesom/admin.py
- bluebottle/funding_vitepay/admin.py
> Change order and hide verified checkbox

- bluebottle/bluebottle_drf2/serializers.py
- bluebottle/wallposts/serializers.py
- bluebottle/wallposts/tests/test_api.py
> Fix & test wallpost photos

- bluebottle/activities/tests/test_models.py
- bluebottle/members/signals.py
segment is added or removed from a user
BB-17549 #resolve
If applicable
> Add a signal that updates the segments of all open activities if a

- bluebottle/funding_flutterwave/views.py
> Log Flutterwave webhooks

- bluebottle/notifications/messages.py
> Filter None from recipient list

- bluebottle/funding/admin.py
- bluebottle/funding_flutterwave/tests/test_admin.py
- bluebottle/funding_flutterwave/tests/test_api.py
- bluebottle/funding_flutterwave/views.py
- bluebottle/funding_stripe/models.py
> Flutterwave sync & anonymous

- bluebottle/assignments/states.py
> Fix assignment state test

- bluebottle/token_auth/views.py
> Fix token auth logout error

- .travis.yml
> Only test python3

- bluebottle/funding_stripe/tests/test_webhooks.py
- bluebottle/funding_stripe/views.py
> Ignore charge calls for intent payments on source endpoint

- setup.py
> Upgrade to new sorl thumbnail

- bluebottle/news/admin.py
> Don't use ImageAdminMixin

- bluebottle/funding_lipisha/utils.py
> Change Lipisha live API

- bluebottle/exports/tests/test_api.py
- bluebottle/exports/views.py
on an expiring signature when downloading an export.
If applicable
> Make sure we actually check if the user is logged in, instead of relying

- bluebottle/funding_telesom/tests/test_api.py
> Fix Telesom test

- bluebottle/bb_accounts/models.py
- bluebottle/categories/models.py
- bluebottle/cms/models.py
- bluebottle/contentplugins/models.py
- bluebottle/files/models.py
- bluebottle/geo/models.py
- bluebottle/mails/models.py
- bluebottle/members/models.py
- bluebottle/news/models.py
- bluebottle/organizations/models.py
- bluebottle/pages/models.py
- bluebottle/settings/base.py
- bluebottle/slides/models.py
- bluebottle/utils/validators.py
- bluebottle/wallposts/models.py
- setup.py
> Make sure we virus scan all uploaded files.

- bluebottle/funding/models.py
- bluebottle/funding/tests/test_api.py
- bluebottle/funding/utils.py
- bluebottle/funding_flutterwave/models.py
- bluebottle/funding_lipisha/models.py
- bluebottle/funding_pledge/models.py
- bluebottle/funding_stripe/models.py
- bluebottle/funding_telesom/models.py
- bluebottle/funding_vitepay/models.py
> Give PSPs a friendly name

- bluebottle/wallposts/serializers.py
- bluebottle/wallposts/tests/test_api.py
> Fix wallposts

- bluebottle/activities/admin.py
- bluebottle/activities/models.py
- bluebottle/assignments/models.py
- bluebottle/events/models.py
- bluebottle/funding/models.py
- bluebottle/time_based/models.py
> Add filter and conistent strings for contributors

- bluebottle/time_based/states.py
> Staff can accept applicants too

- .travis.yml
> Pin diff match patch version

- bluebottle/activities/admin.py
- bluebottle/activities/states.py
- bluebottle/bluebottle_dashboard/templates/admin/base.html
- bluebottle/time_based/messages.py
- bluebottle/time_based/models.py
- bluebottle/time_based/states.py
- bluebottle/time_based/templates/admin/create_on_a_date_duration.html
- bluebottle/time_based/templates/admin/create_period_duration.html
- bluebottle/time_based/tests/test_periodic_tasks.py
- bluebottle/time_based/tests/test_triggers.py
- bluebottle/time_based/triggers.py
> S&T descriptions

- bluebottle/time_based/messages.py
- bluebottle/time_based/states.py
- bluebottle/time_based/templates/admin/create_on_a_date_duration.html
- bluebottle/time_based/templates/admin/create_period_duration.html
- bluebottle/time_based/tests/test_triggers.py
- bluebottle/time_based/triggers.py
> Fix states en tests

- bluebottle/notifications/effects.py
- bluebottle/notifications/templates/admin/notification_effect.html
> Summarize notification effects correctly. And render in template

- bluebottle/activities/admin.py
- bluebottle/activities/effects.py
- bluebottle/activities/models.py
- bluebottle/activities/templates/admin/activities/set_contribution_date.html
- bluebottle/activities/triggers.py
- bluebottle/funding/effects.py
- bluebottle/funding/models.py
- bluebottle/funding/templates/admin/set_contribution_date.html
- bluebottle/funding/tests/test_states.py
- bluebottle/funding/triggers.py
- bluebottle/time_based/models.py
- bluebottle/time_based/tests/test_states.py
> Set start on contributions

- bluebottle/funding/effects.py
- bluebottle/funding/triggers.py
> Fix how we set donation contribution date on contribution

- bluebottle/activities/serializers.py
- bluebottle/activities/tests/test_api.py
- bluebottle/activities/urls/api.py
- bluebottle/activities/views.py
- bluebottle/initiatives/serializers.py
- bluebottle/time_based/models.py
- bluebottle/time_based/serializers.py
- bluebottle/time_based/tests/factories.py
- bluebottle/time_based/tests/test_periodic_tasks.py
- bluebottle/time_based/validators.py
- bluebottle/utils/models.py
> Fix contributors list view

- bluebottle/activities/serializers.py
- bluebottle/activities/utils.py
- bluebottle/geo/serializers.py
- bluebottle/geo/urls/api.py
- bluebottle/geo/views.py
> Always include initiative location

- bluebottle/geo/tests/test_api.py
- bluebottle/geo/views.py
> Paginate and test offices

- setup.py
> Pin xlrd version

- bluebottle/geo/urls/api.py
- bluebottle/geo/views.py
- bluebottle/members/serializers.py
- setup.py
> Load location async on current user

- bluebottle/time_based/periodic_tasks.py
- bluebottle/time_based/templates/mails/messages/new_participant.html
- bluebottle/time_based/templates/mails/messages/new_participant.txt
> Fix some translation weirdisms

- bluebottle/activities/triggers.py
- bluebottle/fsm/effects.py
Hide organizer contribution effects.
If applicable
> Make it possible to hide transition effects.

- bluebottle/activities/migrations/0035_auto_20201130_1337.py
- bluebottle/activities/migrations/0036_auto_20201130_1355.py
- bluebottle/clients/migrations/0003_auto_20201118_1535.py
- bluebottle/time_based/migrations/0036_auto_20201125_1258.py
- setup.py
> Fix contribution start date

- bluebottle/time_based/serializers.py
- bluebottle/time_based/tests/test_api.py
> Fix document url

- bluebottle/bluebottle_dashboard/templates/admin/base.html
> Remove Contributions from main menu

- bluebottle/settings/admin_dashboard.py
- bluebottle/tasks/admin.py
- bluebottle/time_based/admin.py
> Add skills to time based menu

- bluebottle/files/serializers.py
- bluebottle/funding/serializers.py
- bluebottle/time_based/tests/test_api.py
> Fix private document list permissions

- bluebottle/utils/widgets.py
> Fix duration widget if None is set

- bluebottle/activities/states.py
> Make sure we can add Funding through admin

- bluebottle/time_based/migrations/0044_auto_20201224_1120.py
> Fix migration

- bluebottle/time_based/tests/test_periodic_tasks.py
> Smarter date test so it works all days of the month

- bluebottle/time_based/tests/test_api.py
- bluebottle/time_based/views.py
> Do not paginate related participants

- bluebottle/impact/models.py
- bluebottle/time_based/tests/test_api.py
> Allow blank targets in impact goals admin

- setup.py
> Upgrade micawber to get youtube links going again

- bluebottle/bluebottle_dashboard/templates/admin/base.html
Not very pretty fix based on: https://github.com/geex-arts/django-jet/issues/149
> Hack to fix issues with gettext that breaks mutli select boxes

- bluebottle/funding/effects.py
> Don't do dangerous things with pre_save

- bluebottle/initiatives/serializers.py
> Don't show amount or hours if 0

- bluebottle/funding/admin.py
- setup.py
> Add export action to payouts

- bluebottle/activities/serializers.py
- bluebottle/activities/views.py
- bluebottle/bluebottle_drf2/renderers.py
- bluebottle/initiatives/serializers.py
- bluebottle/initiatives/tests/test_api.py
- bluebottle/initiatives/views.py
- bluebottle/time_based/serializers.py
> Add date slots in activity list serializers

- bluebottle/utils/validators.py
> Read more bytes when figuring out the mime type

- bluebottle/geo/admin.py
- bluebottle/initiatives/dashboard.py
- bluebottle/offices/admin.py
- bluebottle/offices/tests/test_admin.py
> Rename some stray subregions

- bluebottle/time_based/serializers.py
> Add start field to period activity list serializer

- bluebottle/bluebottle_dashboard/static/jet/js/src/features/selects.js
- bluebottle/bluebottle_dashboard/templates/admin/base.html
> Fix page block selection

- bluebottle/fsm/management/commands/print_transitions.py
- bluebottle/time_based/triggers.py
- scripts/generate_states_documentation.py
> Add transition documentation for testing

- bluebottle/time_based/serializers.py
> Added onlineMeetingUrl back in meta of period activity

- bluebottle/activities/models.py
- bluebottle/initiatives/models.py
> Rename activity manager

- bluebottle/activities/admin.py
- bluebottle/initiatives/admin.py
> Fix more filters

- bluebottle/activities/admin.py
- bluebottle/funding/admin.py
- bluebottle/time_based/admin.py
> Change date heirchy to activity admin

- bluebottle/activities/filters.py
- bluebottle/activities/tests/test_api.py
> Filter rejected activities by default

- bluebottle/time_based/effects.py
- bluebottle/time_based/tests/test_triggers.py
- bluebottle/time_based/triggers.py
> Add trigger that resets slots selection if there is only one slot left

- bluebottle/time_based/permissions.py
- bluebottle/time_based/tests/test_api.py
- bluebottle/time_based/views.py
> Do not allow editing  / deletion of slots for open activities

- bluebottle/test/utils.py
- bluebottle/time_based/tests/test_admin.py
> Add test to add activity + slots in admin

- bluebottle/time_based/templates/mails/messages/activity_base.html
- bluebottle/time_based/templates/mails/messages/changed_multiple_dates.html
- bluebottle/time_based/templates/mails/messages/changed_single_date.html
- bluebottle/time_based/templates/mails/messages/deadline_changed.html
- bluebottle/time_based/templates/mails/messages/deadline_changed.txt
- bluebottle/time_based/templates/mails/messages/participant_added.html
- bluebottle/time_based/templates/mails/messages/reminder_multiple_dates.html
- bluebottle/time_based/templates/mails/messages/reminder_single_date.html
> Fix some emails

- bluebottle/time_based/templates/mails/messages/partial/slots.html
- bluebottle/time_based/templates/mails/messages/partial/slots.txt
BB-18245 #resolve
If applicable
> Mark which slot has changed

- bluebottle/geo/admin.py
> Make sure we don't always create a place

- bluebottle/geo/fields.py
> Set default srid for points

- bluebottle/exports/resources.py
- bluebottle/exports/tests/test_export.py
- bluebottle/settings/base.py
> Add slots and slot-participants to export

- bluebottle/funding/tests/test_triggers.py
- bluebottle/funding/triggers.py
BB-18005 #resolve
If applicable
> Fix refunding activities

- bluebottle/time_based/messages.py
- bluebottle/time_based/templates/mails/messages/participant_finished.html
- bluebottle/time_based/templates/mails/messages/participant_finished.txt
- bluebottle/time_based/tests/test_triggers.py
- bluebottle/time_based/triggers.py
> Send message when participant is stopped

- bluebottle/deeds/admin.py
- bluebottle/deeds/models.py
- bluebottle/deeds/states.py
- bluebottle/deeds/tests/test_api.py
- bluebottle/deeds/views.py
> Fix how participants sign up for deeds

- bluebottle/time_based/admin.py
> Add capacity to slot admin

- bluebottle/activities/tests/test_admin.py
- bluebottle/activities/triggers.py
> Auto approve after auto submit

- bluebottle/time_based/tests/test_models.py
- bluebottle/time_based/validators.py
> Fix validation of registration deadline

- bluebottle/geo/models.py
- bluebottle/geo/serializers.py
- bluebottle/time_based/admin.py
BB-18264 #resolve
If applicable
> Add help text under the slot start date indicating the timezone.

- bluebottle/initiatives/serializers.py
- bluebottle/initiatives/tests/test_api.py
- bluebottle/statistics/models.py
- bluebottle/statistics/statistics.py
- bluebottle/statistics/tests/test_unit.py
> Add deed stats to initiatives, filter contributions on status

- bluebottle/members/models.py
> Don't crash on users that might have multiple places

- bluebottle/time_based/serializers.py
BB-18412 #resolve
If applicable
> Add location in activity list for period activities.

- bluebottle/deeds/admin.py
- bluebottle/deeds/states.py
> DeedParticipant admin

- bluebottle/notifications/messages.py
- bluebottle/time_based/tests/test_periodic_tasks.py
> Make sure we don't trip on old duplicated mails

- bluebottle/activities/effects.py
- bluebottle/deeds/states.py
- bluebottle/deeds/tests/test_notifications.py
- bluebottle/deeds/tests/test_triggers.py
- bluebottle/deeds/triggers.py
- bluebottle/fsm/effects.py
- bluebottle/initiatives/serializers.py
- bluebottle/initiatives/tests/test_api.py
- bluebottle/statistics/tests/test_unit.py
> Add more deed ransitions

- bluebottle/initiatives/serializers.py
- bluebottle/initiatives/tests/test_api.py
> Correctly filter initiative stats

- bluebottle/activities/serializers.py
- bluebottle/activities/tests/test_api.py
- bluebottle/activities/views.py
- bluebottle/deeds/serializers.py
> Add deed participants to contributor list

- bluebottle/clients/tests/test_commands.py
- bluebottle/deeds/filters.py
- bluebottle/deeds/tests/test_api.py
- bluebottle/deeds/views.py
- bluebottle/test/utils.py
- bluebottle/utils/email_backend.py
> Correctly filter participants of deed. And test this properly.

- bluebottle/deeds/serializers.py
- bluebottle/deeds/states.py
- bluebottle/deeds/tests/test_api.py
- bluebottle/deeds/tests/test_transitions.py
- bluebottle/deeds/urls/api.py
- bluebottle/deeds/views.py
> Add export url to activity serializer. Add view for export url

- bluebottle/files/serializers.py
- bluebottle/initiatives/tests/test_api.py
> Really fix related images

- bluebottle/time_based/tests/test_api.py
- bluebottle/time_based/views.py
BB-18377 #resolve
If applicable
> Add motivation to export.

- bluebottle/activities/filters.py
- bluebottle/initiatives/tests/test_api.py
- bluebottle/time_based/states.py
BB-18411 #resolve
If applicable
> Include full activities in related initiative activities

- bluebottle/files/views.py
- bluebottle/settings/testing.py
> Get random image from provider specified in settings

- bluebottle/funding/states.py
- bluebottle/funding/tests/test_api.py
> Dont allow refund and recalculate for yall

- bluebottle/cms/serializers.py
> Filter all closed activities from list of highlighted activities

- bluebottle/activities/admin.py
> Make sure we don't trip on tuple + list mismatches in admin filters

- bluebottle/deeds/periodic_tasks.py
- bluebottle/deeds/states.py
- bluebottle/deeds/tests/test_periodic_tasks.py
- bluebottle/deeds/tests/test_transitions.py
- bluebottle/deeds/tests/test_triggers.py
- bluebottle/deeds/triggers.py
> Remove running status from deeds

- bluebottle/deeds/states.py
> Allow succeed manually in admin

- bluebottle/time_based/serializers.py
> Add is-online to PeriodActivityListSerializer

- bluebottle/activities/filters.py
- bluebottle/activities/tests/test_api.py
> Add activity type filter for time based activities

- bluebottle/initiatives/models.py
> Tweak admin labels for open initiatives

- bluebottle/exports/resources.py
BB-18507 #resolve
If applicable
> Add custom user fields to slot participant export

- bluebottle/activities/filters.py
- bluebottle/activities/tests/test_api.py
- bluebottle/exports/resources.py
BB-16977 #resolve
If applicable
> Boost activities that are online or require no skill

- bluebottle/categories/tests/test_api.py
- bluebottle/categories/views.py
- bluebottle/initiatives/admin.py
BB-18314 #resolve
If applicable
> Order categories alfabettically

- bluebottle/time_based/filters.py
- bluebottle/time_based/views.py
> Do not filter out own slot participants when filtering on status

- bluebottle/bb_accounts/tests/test_api.py
- bluebottle/members/serializers.py
- bluebottle/members/tests/test_api.py
BB-18475 #resolve
If applicable
> Fix double error when user already exists.

- bluebottle/funding_stripe/models.py
This fixes issues with live account_id's in testing envs
> Fix for incomplete Stripe API response

- bluebottle/deeds/admin.py
> Add filter an search to deeds admin

- bluebottle/funding_stripe/models.py
- bluebottle/funding_stripe/tests/test_webhooks.py
> Never do `on_behalf-of` for non credit card payments

- bluebottle/activities/models.py
BB-18385 #resolve
If applicable
> Make sure that we have the actual class when getting the absolute url.

- bluebottle/time_based/messages.py
> Fix slot reminder breaking

- bluebottle/funding/templates/mails/messages/donation_success_donor.html
- bluebottle/funding/templates/mails/messages/donation_success_donor.txt
> Fix copy in donation success message.

- bluebottle/bluebottle_dashboard/dashboard.py
> Add recently submitted initiatives to list of dashboard widgets.

- bluebottle/funding_stripe/models.py
> Fix some payout account errors in test envs

- bluebottle/activities/filters.py
- bluebottle/activities/utils.py
- bluebottle/settings/base.py
- bluebottle/time_based/documents.py
Fix is_online on activities with multiple dates.
If applicable
> Make sure we use the same distance for matching.

- bluebottle/activities/messages.py
- bluebottle/activities/tests/test_tasks.py
- bluebottle/notifications/messages.py
> Change matching mail subject

- bluebottle/bb_accounts/models.py
- bluebottle/members/admin.py
- bluebottle/members/models.py
> Change copy for member notification settings. Add to new tab.

- bluebottle/activities/filters.py
- bluebottle/activities/tests/test_api.py
- bluebottle/utils/filters.py
> By default sort on activity date

- bluebottle/bluebottle_drf2/serializers.py
- bluebottle/wallposts/serializers.py
- bluebottle/wallposts/tests/test_api.py
> Do not format wallposts to html. Do that work safely on the frontend

- bluebottle/funding/admin.py
> Fix saving donors when not superuser

- bluebottle/funding/documents.py
BB-17757 #resolve
If applicable
> Sort partially funded the same as succeeded.

- bluebottle/funding_flutterwave/models.py
> Disable Paypal for now

- bluebottle/deeds/models.py
BB-18585 #resolve
If applicable
> Make sure we actually import period tasks.

- bluebottle/activities/messages.py
- bluebottle/activities/tasks.py
- bluebottle/activities/templates/mails/messages/matching_activities.html
- bluebottle/activities/templates/mails/messages/matching_activities.txt
- bluebottle/activities/tests/test_tasks.py
Show "no skill needed" correctly.
If applicable
> Only show 3 matches in email.

- bluebottle/initiatives/serializers.py
- bluebottle/initiatives/tests/test_api.py
- bluebottle/time_based/serializers.py
- bluebottle/utils/fields.py
> Make sure that related activities are returned with the correct type

- bluebottle/activities/templates/mails/messages/matching_activities.html
> Add extra classes to make it more responsive

- bluebottle/activities/tasks.py
> Send matching mails once a month

- bluebottle/notifications/models.py
> Add teams to social sharing options

- bluebottle/activities/documents.py
- bluebottle/activities/filters.py
- bluebottle/members/admin.py
> Only add score for donation contributions

- bluebottle/funding/tests/test_states.py
- bluebottle/funding/validators.py
> Don't allow negative amounts

- bluebottle/activities/tests/test_api.py
- bluebottle/activities/tests/test_models.py
- bluebottle/impact/tests/factories.py
- bluebottle/statistics/tests/test_api.py
- bluebottle/statistics/tests/test_unit.py
- bluebottle/time_based/tests/test_triggers.py
- bluebottle/time_based/triggers.py
> Expire, succeed or fill activity when slot is deleted.

- bluebottle/funding/admin.py
- bluebottle/members/admin.py
- bluebottle/members/tests/test_admin.py
> Add KYC to user admin

- bluebottle/geo/admin.py
- bluebottle/members/serializers.py
- bluebottle/members/tests/test_api.py
> Throttle sign up attempts

- bluebottle/initiatives/permissions.py
- bluebottle/initiatives/tests/test_api.py
- bluebottle/initiatives/views.py
> Allow activity manager to edit the initiative

- bluebottle/time_based/admin.py
> Show timezone in slot inline admin.

- bluebottle/time_based/templates/mails/messages/partial/slots.html
> Make timezone bold in emails

- bluebottle/cms/admin.py
- bluebottle/cms/tests/test_admin.py
- setup.py
> Homepage admin

- bluebottle/activities/tasks.py
> Catch errors when recommending and log errors

- bluebottle/activities/documents.py
- bluebottle/time_based/documents.py
> Prefetch related models to speed up indexing

- bluebottle/activities/tests/test_api.py
- bluebottle/time_based/documents.py
> Fix country filter for date activities too

- bluebottle/utils/widgets.py
> Add renreder argument to secure admin url field

- setup.py
> Use new fork for fluent contents

- bluebottle/time_based/effects.py
- bluebottle/time_based/tests/test_periodic_tasks.py
- bluebottle/time_based/triggers.py
contributions for non-periodic activities.
BB-18780 #resolve
If applicable
> Split contribution create effect. Make sure we do not create period

- bluebottle/time_based/serializers.py
- bluebottle/time_based/tests/test_api.py
> Add permissions meta of time contributions

- bluebottle/funding_lipisha/utils.py
> Change API url again

- bluebottle/activities/filters.py
- bluebottle/test/factory_models/accounts.py
- bluebottle/time_based/serializers.py
- bluebottle/time_based/tests/test_serializers.py
> Add fields with slot info to list serializer

- bluebottle/time_based/tests/test_api.py
- bluebottle/time_based/views.py
> Add get method to slot list api calls

- scripts/migrate_nlcares.py
> Tweak migration

- bluebottle/time_based/serializers.py
> Return locations for passed events

- bluebottle/time_based/messages.py
- bluebottle/time_based/tests/test_triggers.py
- bluebottle/time_based/triggers.py
> disable changed mail for multiple slots.

- scripts/migrate_nlcares.py
> Fix if issue in NL Cares migration

- bluebottle/time_based/admin.py
> Fix date activity admin export

- bluebottle/time_based/views.py
> Add date to participant export slots

- bluebottle/time_based/serializers.py
so that card also render correctly when filled with data from detail
endnpoint.
If applicable
> Add slot-info (date_info, location_info) to date activity serializers,

- bluebottle/time_based/messages.py
- bluebottle/time_based/templates/mails/messages/deadline_changed.html
- bluebottle/time_based/templates/mails/messages/deadline_changed.txt
- bluebottle/time_based/tests/test_triggers.py
> Fix period activity change message

- bluebottle/time_based/models.py
> Set JSON API type for time contribution

- bluebottle/time_based/serializers.py
> Add user to my contribution in activity serializer

- bluebottle/initiatives/documents.py
- bluebottle/initiatives/tests/test_api.py
> Fix country filter

- bluebottle/news/tests/test_api.py
- bluebottle/news/views.py
> Fix loading news with duplicated slug

- bluebottle/time_based/admin.py
> Check if obj is not none

- bluebottle/cms/models.py
- bluebottle/cms/tests/test_admin.py
> Add validation + tests for site links

- bluebottle/fsm/admin.py
- bluebottle/time_based/tests/test_admin.py
> Validate inline form before saving

- bluebottle/segments/models.py
- bluebottle/settings/base.py
- bluebottle/token_auth/auth/base.py
- bluebottle/token_auth/tests/test_saml.py
- setup.py
> Add nicer arrayfield widget and test segments

- bluebottle/bluebottle_dashboard/static/admin/css/dashboard.css
- bluebottle/bluebottle_dashboard/static/admin/css/icon-style.css
- bluebottle/segments/admin.py
> Fix arrayfield admin

- bluebottle/time_based/serializers.py
- bluebottle/time_based/views.py
> Filter withdrawn slot participants

- bluebottle/settings/base.py
- bluebottle/wallposts/tests/test_api.py
> Update rate limit for wallposts to 10 per hour

- bluebottle/time_based/tests/test_api.py
- bluebottle/time_based/views.py
> Allow invalid values for dates in slot lists. Fix internal server error

- bluebottle/clients/utils.py
> Don't use https for localhost mails

- bluebottle/deeds/states.py
- bluebottle/time_based/states.py
> Do not hide cancel transition from admin

- bluebottle/categories/serializers.py
> BB-19105 Use id as id

- bluebottle/utils/models.py
- bluebottle/utils/tests/test_unit.py
> Prevent unkown languages from being saved

- bluebottle/funding/models.py
> Do not fail if a related funding has no target set

- bluebottle/deeds/states.py
- bluebottle/deeds/tests/test_transitions.py
- bluebottle/test/utils.py
BB-19173 #resolve
If applicable
> Only allow succeed_manually transition when there are contributors.

- bluebottle/collect/admin.py
- bluebottle/collect/tests/test_admin.py
> Hide the contributor we create for reporting purposes

- bluebottle/activities/views.py
- bluebottle/collect/documents.py
> Add document for collect activities

- .travis.yml
> Pin wheel and mercurial so Travis is happy

- bluebottle/activities/templates/mails/messages/participant_withdrew_confirmation.html
- bluebottle/deeds/templates/mails/messages/deed_participant_joined.html
- bluebottle/time_based/templates/mails/messages/participant_applied.html
- bluebottle/time_based/templates/mails/messages/participant_changed.html
- bluebottle/time_based/templates/mails/messages/participant_joined.html
> Remove headers from ocnfirmation emails

- bluebottle/time_based/views.py
> Add timezone to slot participant export

- bluebottle/time_based/serializers.py
BB-19260 #resolve
If applicable
> Put back slot count on date activity meta

- bluebottle/collect/messages.py
- bluebottle/collect/templates/mails/messages/collect_participant_joined.html
- bluebottle/collect/tests/test_triggers.py
- bluebottle/collect/triggers.py
- bluebottle/test/utils.py
- bluebottle/time_based/messages.py
- bluebottle/time_based/templates/mails/messages/new_participant.html
- bluebottle/time_based/tests/test_notifications.py
> Add all missing emails for collect activities

- bluebottle/activities/utils.py
- bluebottle/bb_accounts/tests/test_api.py
- bluebottle/bb_accounts/views.py
> Fix the current user slot participant

- bluebottle/collect/tests/test_api.py
- bluebottle/collect/views.py
- bluebottle/deeds/models.py
- bluebottle/deeds/serializers.py
- bluebottle/deeds/tests/test_api.py
- bluebottle/deeds/urls/api.py
- bluebottle/deeds/views.py
- bluebottle/utils/views.py
> Add calendar links to deed serializer

- bluebottle/collect/serializers.py
impact is enabled.
If applicable
> Add goals to serializer. This way the slider will update directly when

- bluebottle/funding/serializers.py
- bluebottle/funding/tests/test_api.py
> Fix bug with co-financing organizers

- bluebottle/collect/tests/test_api.py
- bluebottle/collect/views.py
> Fix ical view for Collect + test

- bluebottle/time_based/states.py
> Allow cancel in admin

- .travis.yml
> Fix elasticsearch in travis

- bluebottle/activities/admin.py
> Fix addin activities with the new segments admin fields

- bluebottle/segments/admin.py
- bluebottle/segments/models.py
- locale/nl/LC_MESSAGES/django.po
BB-19432 #resolve
If applicable
> Update admin help texts for segments.

- bluebottle/activities/utils.py
- bluebottle/initiatives/serializers.py
- bluebottle/segments/serializers.py
- bluebottle/segments/tests/test_api.py
- bluebottle/segments/views.py
> Fix activity and initiatives count for segment api

- bluebottle/segments/serializers.py
> change from 82x82 to 180x180

- bluebottle/time_based/tests/test_periodic_tasks.py
> Test closing of activity when slot closes

- bluebottle/segments/models.py
- bluebottle/segments/tests/test_admin.py
- bluebottle/settings/admin_dashboard.py
> Fix segment field names in admin

- bluebottle/segments/serializers.py
- bluebottle/segments/urls/api.py
> Fixes for branded signup page

- bluebottle/bb_accounts/views.py
- bluebottle/members/serializers.py
- bluebottle/members/tests/test_api.py
- bluebottle/segments/migrations/0024_auto_20220210_1336.py
> Fix the captcha form

- bluebottle/bb_accounts/tests/test_api.py
- bluebottle/members/models.py
- bluebottle/members/serializers.py
- bluebottle/members/tests/test_api.py
Verify segments when updating them through the API.
BB-19610 #resolve
> Add unverified segments to required field in member API.

- bluebottle/funding/tests/test_api.py
- bluebottle/funding/views.py
> Only show succeeded donations in export

- bluebottle/scim/serializers.py
- bluebottle/scim/tests/test_api.py
- bluebottle/scim/views.py
- setup.py
Add office location to SCIM API.
> Actually parse and execute patch requests.

- bluebottle/activities/serializers.py
- bluebottle/activities/tests/test_api.py
- bluebottle/activities/urls/api.py
- bluebottle/activities/utils.py
- bluebottle/activities/views.py
- bluebottle/test/utils.py
Make sure we include the team and the owner of the team in the response.
BB-19789 #resolve
> Add invite endpoint

- bluebottle/bb_accounts/templates/bb_accounts/password_reset_email.html
- bluebottle/bb_accounts/tests/test_api.py
- bluebottle/bb_accounts/tests/test_models.py
- bluebottle/members/templates/mails/messages/account_activation.html
- bluebottle/time_based/triggers.py
sometimes loose access to the rset token somehow.
BB-19886 #resolve
> Link directly to the password set url. The redirects in the frontend

- bluebottle/time_based/states.py
- bluebottle/time_based/tests/test_states.py
> Do not allow a finish transition for period participants that are part

- bluebottle/activities/utils.py
- bluebottle/deeds/tests/test_api.py
This way team member cannot invite other users
> Hide the invite for user that accepted an invite.

- bluebottle/activities/models.py
- bluebottle/time_based/tests/test_api.py
- bluebottle/time_based/views.py
- bluebottle/utils/admin.py
- bluebottle/utils/views.py
Also make it possible to override the XlS generation method in
ExportView
> Add Teams sheet when activity is a team activity.

- bluebottle/segments/tests/test_api.py
- bluebottle/segments/views.py
Add tests for related segment view. Filter closed segments from related
list.
> Do not paginate related segments.

- bluebottle/segments/migrations/0007_auto_20220119_0945.py
- bluebottle/suggestions/migrations/0001_initial.py
- bluebottle/suggestions/migrations/0005_auto_20210302_1417.py
that causes issues for new tenants
> Remove old migration

- bluebottle/funding/messages.py
- bluebottle/funding_stripe/tests/test_triggers.py
with submitted_initiative_notifications
> Send KYC rejected to members

- bluebottle/activities/dashboard.py
- bluebottle/activities/models.py
- bluebottle/activities/templates/dashboard/recent_contributors.html
- bluebottle/bluebottle_dashboard/dashboard.py
- bluebottle/wallposts/dashboard.py
- bluebottle/wallposts/templates/dashboard/recent_wallposts.html
> Add widget for recent contributions & wallposts

- bluebottle/activities/filters.py
- bluebottle/activities/tests/test_api.py
- bluebottle/initiatives/filters.py
- bluebottle/utils/filters.py
Add current filter if facet is not present.
> Use models for finding labels of facets.

- docker-compose.yml
Also mv all docker data directories to single docker dir.
> Mount base dir as volume. Set working dir to this volume/

- bluebottle/activities/serializers.py
This is 2x the display size on desktop view
> Improve image quality for activity

- bluebottle/activities/utils.py
Small change to save a duplicated activity
> Fix serializer for duplicated activities

- bluebottle/time_based/tests/test_scenarios.py
- bluebottle/time_based/tests/test_triggers.py
- bluebottle/time_based/triggers.py
This makes sure that participants do not become 'withdrawn' or 'removed'
> Remove participant triggers from slot participants

- bluebottle/time_based/admin.py
- bluebottle/time_based/states.py
- bluebottle/time_based/templates/admin/time_based/bulk_add.html
- bluebottle/time_based/templates/admin/time_based/dateactivityslot/change_form.html
- bluebottle/time_based/utils.py
> Add bulk add feature

- bluebottle/time_based/states/participants.py
> Change withdraw copy

- bluebottle/time_based/admin.py
> Move management to first tab

- bluebottle/time_based/templates/admin/time_based/registration_info.html
> Change review call out in admin

- bluebottle/time_based/admin.py
- bluebottle/time_based/models.py
Participant count was not calculated correctly and it woudl show 0
> Fix some status checks

- bluebottle/time_based/admin.py
> Structure fields

- bluebottle/time_based/notifications/registrations.py
- bluebottle/time_based/templates/mails/messages/registrations/user_restarted.html
- bluebottle/time_based/templates/mails/messages/registrations/user_stopped.html
- bluebottle/utils/widgets.py
> Change copy

- bluebottle/time_based/models.py
- bluebottle/time_based/serializers/activities.py
- bluebottle/time_based/serializers/participants.py
- bluebottle/time_based/serializers/slots.py
- bluebottle/time_based/serializers/teams.py
- bluebottle/time_based/states/participants.py
- bluebottle/time_based/urls/schedule_api.py
- bluebottle/time_based/views/participants.py
> Add 'my' to related link field

- bluebottle/time_based/models.py
- bluebottle/time_based/validators.py
> Validate deadline is after start date

- bluebottle/activities/permissions.py
- bluebottle/time_based/models.py
- bluebottle/time_based/views/teams.py
Allow AM to change team so Manage menu shows
> Allow AM to change team

- bluebottle/time_based/templates/mails/messages/registrations/manager_team_registration_created.html
- bluebottle/time_based/templates/mails/messages/registrations/manager_team_registration_created_review.html
> Change email for new team

- bluebottle/slides/admin.py
- bluebottle/slides/models.py
> Make empty value label 'Global'

- bluebottle/funding/serializers.py
> Change error when amoun below reward

- bluebottle/updates/models.py
- bluebottle/updates/serializers.py
> Fake name on donation wallposts

- bluebottle/statistics/models.py
- bluebottle/statistics/statistics.py
- bluebottle/statistics/tests/test_api.py
- bluebottle/statistics/views.py
> Add collect stat to user

- bluebottle/activities/filters.py
- bluebottle/activities/tests/test_api.py
This fixes the search error we get for NL Cares, because `theme` is not a set filter
> Dynamically add filters to facets

- bluebottle/activities/admin.py
- bluebottle/activities/templates/admin/activities/bulk_add.html
- bluebottle/activities/utils.py
- bluebottle/bluebottle_dashboard/static/admin/css/dashboard.css
- bluebottle/collect/templates/admin/collect/collectactivity/change_form.html
- bluebottle/deeds/templates/admin/deeds/deed/change_form.html
- bluebottle/time_based/templates/admin/time_based/bulk_add.html
- bluebottle/time_based/templates/admin/time_based/dateactivityslot/change_form.html
- bluebottle/time_based/templates/admin/time_based/deadlineactivity/change_form.html
> Add bulk add feature to admin activities

- bluebottle/activities/admin.py
- bluebottle/activities/templates/admin/activities/bulk_add.html
- bluebottle/bluebottle_dashboard/static/admin/css/dashboard.css
> Fix some copy & style for bulk add

- bluebottle/time_based/views/exports.py
This reverts commit 0bc8ac6a9424e691cbb7d05dc60c39348784d2db.
> Reapply "Do not add segments for participants without an user"

- bluebottle/funding/models.py
- bluebottle/funding/templates/mails/messages/donation_success_donor.html
- bluebottle/funding/templates/mails/messages/donation_success_owner.html
- bluebottle/funding/templates/mails/messages/partials/donation_receipt.html
- bluebottle/notifications/templates/mails/styling/mail.css
> Improve donation receipt

- bluebottle/bluebottle_dashboard/static/admin/css/dashboard.css
> Fix alignment of checkbox labels

- bluebottle/activities/models.py
- bluebottle/activities/states.py
> Fix initiative/image/theme requirement

- bluebottle/initiatives/models.py
> Fix filter placeholder

- bluebottle/activities/serializers.py
> Fix my contributions

- bluebottle/funding/admin.py
- bluebottle/funding/models.py
- bluebottle/utils/fields.py
> Use currency

- bluebottle/funding_stripe/admin.py
- bluebottle/funding_stripe/models.py
Moved verification link to first page, account id to superadmin.
> Improve payout admin

- bluebottle/funding/adapters/rabobank.py
- bluebottle/funding/models.py
We don't have access yet, so we can't really test :-(
> Add Rabobank adapter for IBAN check

- bluebottle/grant_management/admin.py
- bluebottle/grant_management/models.py
- bluebottle/notifications/messages.py
> New balance tab for funds
