onepercentclub/bluebottle

bluebottle/bluebottle_drf2/serializers.py
We're not using it and it breaks if the file isn't present.
=> Don't serialize file size for private files.

bluebottle/bb_payouts/models.py, bluebottle/bb_payouts/signals.py
The invoice reference for ProjectPayouts was set in a the project's
post_save signal handler. As far as I can tell, that is the only way
that payouts are created. However the database of onepercent contains
payouts that do not have the invoice_reference being set.
By moving this to the save method, we will know for sure that the
invoice reference is set. As far as I can tell, this should always be
the case.
=> Set the invoice_reference in the save method

bluebottle/bb_accounts/models.py, bluebottle/bb_projects/models.py, bluebottle/bb_tasks/models.py, bluebottle/exports/forms.py, bluebottle/exports/resources.py, setup.py
This is a first set of performance changes/extra features to export the database.
I've added custom ExportResource classes so we can leverage select_related and filter the queryset on a daterange.
Some computed fields on exported objects are cached because they are reused in different properties. This effectively reduces the number of queries.
In a further step I want to look into further reducing the number of queries.
=> Exportdb fixes

bluebottle/common/tests/test_unit.py, dashboard.py
The adopted field in the metrics was querying for projects with the state submitted and a project reference. All submitted projects have a project reference, so this status was redundant.
=> Remove `adopted` from suggestion metrics

bluebottle/common/tasks.py, bluebottle/wallposts/signals.py
* Delay sending to facebook, since the images are hooked up after the creation of the wallpost. This is a bit of a hack, but fixing the wallpost creation is much, much more work.
* Put the url in the caption, and the message above the image.
=> Delay sending to facebook, fix caption and message

bluebottle/projects/models.py
If the ordering is undetermined (for example when all projects have popularity 0), postgres will order randomly, and the ordering will change depending on the offset.
=> Fix random ordering in search

bluebottle/categories/models.py, bluebottle/categories/tests/test_unit.py
Note that the standard method of prepopulated fields does not work if you exclude the slug field in the admin
=> Automattically fill the slug for categories. 

bluebottle/settings/base.py, setup.py
When uploading a file with an identical filename on more then one
tenant, sorl thumbnail generates the same kv cache key for all the
files. This means the file can only be retrieved for one of the tenants.
One way to hit this issue is by using facebook to login for more then 1
tenant. Since facebook send the same filename to each tenant, only one
tenant will show a profile image.
This change makes sure we have a separate kv store for each tenant, so
that we do not have these conflicts.
The reason we install sorl from github is that the version on pypi does not have the migrations packaged (and essentially is not django-1.9 compatible.
=> Make sorl.thumbnail a tenant app

bluebottle/projects/management/commands/cron_status_realised.py, bluebottle/projects/tests/test_management.py, bluebottle/tasks/models.py
Waiting for confirmation that an open task should be closed when it's deadline is reached.
=> Set task status to closed when an open task exceeds its deadline BB-7538

bluebottle/bb_follow/admin.py, bluebottle/wallposts/admin.py, bluebottle/wallposts/mails.py, bluebottle/wallposts/models.py, bluebottle/wallposts/tests/test_api.py
+ Show 'deleted' wallposts & reactions in admin
+ Don't send mails on wallpost/reaction 'delete' or update. Only on create
+ Regression test
+ Add admin for Follow
=> Fix multiple mails on wp/reaction

bluebottle/bb_payouts/signals.py
Reverts onepercentclub/bluebottle#2206
Somehow this breaks the db export.
=> Revert "Make sure payout signal accepts double payouts."

bluebottle/auth/middleware.py
This fixes multipart POSTs when lock-down is enabled.
Touch request.POST before DRF process the requests breaks multipart
messages in DRF. By checking if the content-type is
application/www-formencoded we do not touch request.POST, not exposing
this bug.
BB-7841 #resolve
=> Only check lockdown form on form-encoded requests

bluebottle/analytics/tests/test_api.py, bluebottle/analytics/tests/test_models.py, bluebottle/bb_accounts/tests/test_models.py, bluebottle/bb_tasks/tests/__init__.py, bluebottle/bb_tasks/tests/test_api.py, bluebottle/bb_tasks/tests/test_mails.py, bluebottle/bb_tasks/tests/test_models.py, bluebottle/bb_tasks/views.py, bluebottle/tasks/admin.py, bluebottle/tasks/models.py, bluebottle/tasks/serializers.py, bluebottle/tasks/signals.py, bluebottle/tasks/tests/test_api.py, bluebottle/tasks/tests/test_mails.py, bluebottle/tasks/tests/test_models.py, bluebottle/tasks/tests/test_unit.py
* Don't remove taskmember records if they withdraw
* Move taskmember count to a signal
* Add/adjust tests
* PEP8 tasks/bb_tasks
=> Soft delete taskmembers

bluebottle/tasks/admin.py
Task admin link breaks if title has an accented character
=> Handle accented titles in project / task list

bluebottle/projects/admin.py, bluebottle/projects/models.py, bluebottle/projects/templates/admin/projects/project/change_form.html, bluebottle/projects/tests/test_admin.py
- Only show in list_fields and list_displays if the user has permission
- Make payout status readonly
- Do permission check in approve_payout
BB-9050 #resolve
=> Only show payout_status fields if the user has the correct permissions.

bluebottle/tasks/tests/test_mails.py, bluebottle/utils/email_backend.py
Fixes recipient name being empty in (among others) task emails.
BB-9338 #resolve
=> Add the recipient to the email template context.

bluebottle/cms/serializers.py, bluebottle/statistics/statistics.py
* Do not return all project images (we do not show them anyway)
* Cache maps result
* Extend caching from 5 minutes to an hour
BB-9263 #resolve
=> Speed up result pages

bluebottle/payouts_dorado/adapters.py
we do not override that status that dorado set.
BB-9471 #resolve
=> Set the payout status to created BEFORE we call out to dorado. This way

bluebottle/homepage/models.py, bluebottle/homepage/tests/test_api.py
=> Send an empty list instead of None if no projects

bluebottle/payouts_dorado/adapters.py, bluebottle/projects/tests/test_admin.py
This is not a a valid choice in the model. If something goes wrong
during the payout creation, this status will not show, and it will not
be possible to change the status.
Under normal conditions, the status would only be set to "created"
while waiting for the payout app do do the status callback. So in that
situation, it also is not useful,
BB-9613 #resolve
=> Do not mark payments as created.

bluebottle/analytics/tasks.py
Fixes the error below found in **/var/log/celery/worker.log**
> [2017-05-04 00:15:00,149: ERROR/MainProcess] Task bluebottle.analytics.tasks.generate_engagement_metrics[e1f002f5-a680-4615-b8f4-de6ef653a803] raised unexpected: CommandError(u'Error: argument --start is required',)
Traceback (most recent call last):
File "/var/www/reef-prod/api/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
R = retval = fun(*args, **kwargs)
File "/var/www/reef-prod/api/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
return self.run(*args, **kwargs)
File "/var/www/reef-prod/api/releases/20170502-1842-69237962c7fe21ba6ffe5260a5d1e7d849fe4fff/bluebottle/analytics/tasks.py", line 48, in generate_engagement_metrics
'--end', …
=> remove extra space before start param

bluebottle/bb_tasks/permissions.py, bluebottle/bb_tasks/tests/test_api.py, bluebottle/tasks/serializers.py
=> add time_spent to task member serializer

bluebottle/projects/serializers.py, bluebottle/projects/tests/test_api.py
For some reason did not escape the title in the frontend, but did it in the backend.
That is not the standard way of doing things, and cause issues with place were we expect unescaped strings.
=> Do not escape title. This should be escaped in the fronten'

bluebottle/tasks/migrations/0021_auto_20170503_1435.py
The migration failed on the server with:
django.db.utils.OperationalError: cannot ALTER TABLE "tasks_task"
because it has pending trigger events
See
http://stackoverflow.com/questions/28429933/django-migrations-using-runpython-to-commit-changes
on why this fixes that issue.
=> Fix migration.

bluebottle/clients/tests/test_api.py, bluebottle/clients/utils.py, bluebottle/settings/base.py
And refactor exposed settings so nested settings can be more explicitly defined. We should have to be explicit so we don't accidentally expose settings. 
BB-9496 #resolve
=> Add default exposed settings for tasks / cv upload

.travis.yml, bluebottle/categories/admin.py, bluebottle/categories/models.py
- Remove WYSIWYG editor from content block description
- Fix labels as requested in BB-10296 (see invision attachment in the ticket)
=> category block enhancements

bluebottle/analytics/management/commands/export_engagement_metrics.py, bluebottle/analytics/utils.py, bluebottle/orders/signals.py, bluebottle/projects/models.py, bluebottle/recurring_donations/admin.py, bluebottle/tasks/models.py
With using `properties` instead of `settings` we can overwrite `CELERY_RESULT_BACKEND` for tenants. This way we can temporarily shut it off for VjB. Otherwise all new orders will set a timeout totally over flooding the celery queue in rabbitmq.
=> Make celery tenant overwritable

bluebottle/bb_accounts/templates/bb_accounts/activation_email_no_password.html, bluebottle/bb_accounts/templates/bb_accounts/activation_email_no_password.txt, bluebottle/bb_accounts/tests/test_api.py, bluebottle/bb_accounts/utils.py, bluebottle/members/admin.py, bluebottle/members/tests/test_admin.py, bluebottle/test/utils.py
- send password reset email when creating user
- user is now active by default when created
- hide voting and address details when creating user
BB-10287 #resolve
=> Updates for user creation in the BO

bluebottle/bb_tasks/templates/task_member_realized.mail.html, bluebottle/bb_tasks/templates/task_member_realized.mail.txt, bluebottle/bb_tasks/templates/task_member_rejected.mail.html, bluebottle/bb_tasks/templates/task_member_rejected.mail.txt, bluebottle/bb_tasks/urls/api.py, bluebottle/bb_tasks/views.py, bluebottle/tasks/permissions.py, bluebottle/tasks/serializers.py, bluebottle/tasks/taskmail.py, bluebottle/tasks/tests/test_api.py
users.
Adds an API endpoint /api/tasks/members/status/id that makes it possible
to get and set the status of a taskmember. A message has to be passed in
that will become part of the email send to the member.
BB-9498 #resolve
=> Make it possible to send custom messages when confirming / rejecting

bluebottle/donations/admin.py, bluebottle/projects/admin.py, bluebottle/projects/templates/admin/projects/project/change_form.html, bluebottle/projects/tests/test_admin.py
- Just check if user is staff. There are no read permissions in the
admin
- Add user's name to donation export
BB-10995 #resolve
BB-11141 #resolve
=> Fix permission checking for reward export.

bluebottle/bb_orders/models.py, bluebottle/bb_orders/signals.py, bluebottle/payments/admin.py, bluebottle/payments/signals.py, bluebottle/payments/tasks.py, bluebottle/payments/tests/test_admin.py, bluebottle/payments/tests/test_models.py, bluebottle/payments_docdata/admin.py
* Don't transition successful orders to failed if one (order)payment fails
* Make bulk checking payment status check a celery task
* Friendly errors when doing payment status check (avoid server errors)
*NB: Since this changes some inner workings of payments it needs thorough reviewing.*
=> Fix payment handling

bluebottle/cms/content_plugins.py, bluebottle/cms/serializers.py, bluebottle/cms/tests/test_api.py, bluebottle/test/factory_models/cms.py
and training them in changing the homepage in the admin is too
complicated, let the homepage use the existing slides models.
The new slides models are left in, because when we do expose changing
the homepage to normal users, we will need them again.
=> Since tenants regularly changes slides that appear on the homepage,

bluebottle/common/management/commands/makemessages.py
This way the translations do not contain accidental changes.
=> Make sure we always use the same filename for the fixtures translations.

bluebottle/analytics/management/commands/create_report_fixtures.py, bluebottle/analytics/management/commands/create_report_views.py, bluebottle/analytics/management/commands/export_analytics_data.py, bluebottle/analytics/management/commands/export_engagement_metrics.py, bluebottle/analytics/management/commands/export_participation_metrics.py, bluebottle/analytics/management/commands/export_report.py, bluebottle/clients/management/commands/bulk_import.py, bluebottle/clients/utils.py, bluebottle/cms/management/commands/migrate_homepage.py, bluebottle/common/tasks.py, bluebottle/donations/management/commands/export_donations.py, bluebottle/members/management/commands/convert_wp_passwords.py, bluebottle/orders/tasks.py, bluebottle/payouts/management/commands/export_payouts.py, bluebottle/payouts_dorado/management/commands/export_keys.py, bluebottle/projects/management/commands/cron_status_realised.py, bluebottle/projects/tasks.py, bluebottle/recurring_donations/management/commands/process_monthly_donations.py, bluebottle/recurring_donations/tasks.py, bluebottle/surveys/management/commands/sync_surveys.py, bluebottle/surveys/tasks.py, bluebottle/tasks/taskmail.py
context manager.
Also set the db connection correctly. I so no usecase where we would not
want that. But it easy to forget and mess up.
Remove the duplicate calls to set_tenant everywhere.
=> Make sure we flash the content types cache when entering the LocalTenant

bluebottle/tasks/serializers.py, bluebottle/tasks/tests/test_api.py
This fixes confirming task members where the task author is also a
member. In that case the check would falsely mark the member as
duplicate.
BB-11820 #resolve
=> Do not check if the task member is duplicate for existing tasks.

bluebottle/bb_tasks/templates/task_member_realized.mail.html, bluebottle/bb_tasks/templates/task_member_realized.mail.txt, bluebottle/tasks/models.py, bluebottle/tasks/taskmail.py, bluebottle/tasks/tests/test_mails.py, bluebottle/tasks/tests/test_unit.py
Marking a task member as absent, sets it's hours to 0. A normal task
realized mail will be sent.
Add the number of hours in the email.
BB-11590 #reslove
BB-11922 #reslove
=> Make it possible to mark task members as absent

bluebottle/payments/models.py
With this way we should be able to update payments that went from _refund requested_ to _settled_.
=> Allow refund(request)ed to failed/settled transitions.

bluebottle/auth/handlers.py
Updated a broken link reference that was moved from:
http://django-rest-swagger.readthedocs.org/en/latest/settings.html#resource-access-handler
to
https://django-rest-swagger.readthedocs.io/en/stable-0.3.x/settings.html#resource-access-handler
=> Update broken external link

bluebottle/tasks/signals.py, bluebottle/tasks/tests/test_mails.py
We did not update task._init_status, which made the call to
send_realized_mail happen for every updated taskmember within a request.
This fixes this. This does however not fix the race condition when
updating multiple task members in the frontend.
=> Do not call status_changed for every task member that is changed.

bluebottle/projects/management/commands/cron_status_realised.py
deadline reached.
Without this, we will not continue with the command if somethign fails, and other tenants
will not be updated.
=> Make sure that we catch exceptions when updating statuses in cron

bluebottle/settings/base.py
host ourselves.
The bootstrap version bundled with drf has a security issue that takes
forever to be fixed. For now we disable the styled interface completely.
Summernote loads some files over a cdn by default, since we also host
these files, we might aswell use those. This way we also do not need to
worry about the security implications.
=> Do not show bootstrap interface for drf api. Do not use cdn for files we

bluebottle/members/admin.py, bluebottle/members/tests/test_admin.py
Non-super users can no longer assign groups to user that they are not
part of themselves.
Non-super users can no longer change the email of other staff users.
It is no longer possible to directly set the password of users.
=> Fix privilige escalation in backoffice

bluebottle/projects/migrations/0080_auto_20180828_1049.py
This will break the old code running against the migrated db, resulting
in downtime during the release.
We should remove this field when the changes are deployed.
=> Do not remove popularity field from db for now.

bluebottle/cms/urls/api.py
and we (incorrectly) use 'homepage' as the id.
=> Do not add a slash to the url. Ember does not like slashes after the id,

bluebottle/payments_stripe/adapters.py, bluebottle/payments_stripe/tests/test_adapters.py, bluebottle/payments_stripe/tests/test_webhooks.py, bluebottle/payments_stripe/views.py
When a charge fails, handle this correctly. This will make sure we mark
failed credit card donations correctly as charged.
When a source has no charge but is marked as consumed, mark it as
failed.
=> Small fixes for the stripe adapter:

bluebottle/wallposts/mails.py, bluebottle/wallposts/tests/test_api.py
Make sure we do not send the message when a donation is attached.
BB-14343 #resolve
=> Also send a mail to the object's owner when a MediaWallpost is created.

bluebottle/payments_stripe/adapters.py, bluebottle/payments_stripe/tests/test_adapters.py
Instead rely on the `charge.succeeded` event to update the payments.
This wat we do not create 2 wallposts and only send one email.
BB-14537 #resolve
=> Do not update stripe payment after charge.

bluebottle/initiatives/models.py, bluebottle/initiatives/serializers.py, bluebottle/initiatives/tests/test_model.py, bluebottle/initiatives/tests/test_transitions.py, bluebottle/initiatives/transitions.py
Always set `has_organization` when setting is set to true.
Validate submit transition correctly when `has_organization` is true.
BB-14454 #resolve
=> Require organization when settings is set to true.

bluebottle/activities/serializers.py, bluebottle/funding/tests/test_api.py, bluebottle/test/factory_models/geo.py
In the activities list call, the place or location of the initiative wasn't included. This is used in the funding cards.
=> adds initiative.location and initiative.place to activities serializer

bluebottle/utils/tests/test_unit.py, bluebottle/utils/utils.py
=> Make sure we strip spaces for ip address taken from the

bluebottle/activities/serializers.py
This prevents an error when going from an activity to an inititiatve
with an organization.
BB-15586 #resolve
=> Add organization and organization contact to activity detail serializer.

bluebottle/activities/transitions.py, bluebottle/assignments/tests/test_transitions.py, bluebottle/assignments/transitions.py, bluebottle/events/tests/test_transitions.py, bluebottle/events/transitions.py
- Make sure that when an event closes, all participants become closed
- When an assignment closes, applicants should be closed too, not failed
- When an applicant succeeds, set the time spent to the duration of the
assignment.
BB-15615 #resolve
=> Fix assignment and event transitions

bluebottle/events/models.py, bluebottle/events/tests/test_models.py
The previous will set the timzone to 'Europe/Amsterdam LMT +00:20` ofr
some obscure reason.
Timezone.localize will work correctly.
BB-15726 #resolve
=> Use timezone.localize instead of time.replace(timezone).

bluebottle/funding/messages.py, bluebottle/funding/models.py, bluebottle/funding/templates/mails/messages/payout_account_rejected.html, bluebottle/funding/templates/mails/messages/payout_account_rejected.txt, bluebottle/funding/templates/mails/messages/payout_account_verified.html, bluebottle/funding/templates/mails/messages/payout_account_verified.txt, bluebottle/funding/transitions.py, bluebottle/funding_stripe/models.py, bluebottle/funding_stripe/tests/test_models.py, bluebottle/funding_stripe/tests/test_webhooks.py, bluebottle/funding_stripe/transitions.py, bluebottle/funding_stripe/views.py, bluebottle/utils/email_backend.py
Send message to owner when account is rejected / verified
Fix webhook, reject account when status becomes unverified.
Use status for verification check. This is much faster, since it does
not require a call to stripe.
BB-14634 #resolve
=> Try to submit all fundings when a payout account is submitted.

bluebottle/files/serializers.py
Calculating the md5 of a unicode filename will fail, breaking the
serializer.
BB-16045 #resolve
=> Fix unicode filenames in cache bust parameter.

bluebottle/notifications/messages.py
test_send_translated_messages
self.assertEqual(mail.outbox[0].subject, "Test message")
AssertionError: u'Test bericht' != 'Test message'
=> Force unicode in subject field

setup.py
BB-16369 #resolve
Dragging links and linkgroups and saving them works again with this update.
=> Update adminsortable to fix link ordering

bluebottle/members/serializers.py, bluebottle/members/tests/test_api.py, bluebottle/utils/serializers.py
=> Make sure that long paths do not cause errors when recording user

bluebottle/bb_accounts/views.py, bluebottle/members/tests/test_api.py
or their password.
If applicable
=> Make sure we invalidate the token when updating their email address and

bluebottle/wallposts/serializers.py, bluebottle/wallposts/tests/test_api.py, bluebottle/wallposts/urls/api.py, bluebottle/wallposts/views.py
Make sure it is not possible to change to owner of a wallpost in the
API.
Make sure it is not possible to change the wallpost of a wallpost photo
to a wallpost with a different owner.
If applicable
=> Fix wallpost and wallpost photo permissions.

bluebottle/assignments/models.py, bluebottle/cms/models.py
=> Enable activities block plugin for results page

bluebottle/funding_stripe/models.py, bluebottle/funding_stripe/tests/test_webhooks.py
information is missing.
BB-16754 #resolve
If applicable
=> Set stripe payout accounts to incomplete instead of to rejected when

bluebottle/events/admin.py
BB-16853 Can't adjust activity descriptions "Details" in the backoffice + front end
https://onepercentclub.atlassian.net/browse/BB-16853
If applicable
=> Disable registration-deadline from event admin

bluebottle/scim/scim_data/resource_types.py
SCIM does not support that. For us this extension is not required
either, so no need to specify it as such.
If applicable
=> Make sure that the scim enterprise user extension is not required. DSM

bluebottle/funding_stripe/tests/factories.py, bluebottle/funding_stripe/tests/test_webhooks.py, bluebottle/funding_stripe/views.py
If we receive a webhook for a payment intent. Try to get the payment
from the donation and set the current intent as the payments intent.
If applicable
=> Support having more then one payment intent on a donation.

bluebottle/funding_stripe/models.py, bluebottle/funding_stripe/tests/test_api.py, bluebottle/funding_stripe/tests/test_webhooks.py
=> Make it possible to create and transfer to non-european connect accounts

bluebottle/activities/states.py, bluebottle/events/states.py, bluebottle/events/tests/test_api.py, bluebottle/fsm/effects.py, bluebottle/fsm/serializers.py, bluebottle/funding/states.py, bluebottle/initiatives/tests/test_states.py
initiative.
Fix effects when auto-submitting events.
If applicable
=> Never auto-submit funding activities. Also not when approving the

bluebottle/assignments/states.py
=> Set organizer to when restoring an assigment

bluebottle/assignments/models.py, bluebottle/assignments/periodic_tasks.py, bluebottle/assignments/states.py, bluebottle/assignments/tests/test_tasks.py, bluebottle/assignments/triggers.py
=> Also mark new applicants succeeded when an assignment is succeeded

bluebottle/funding/models.py, bluebottle/funding/tests/test_admin.py, bluebottle/initiatives/models.py, bluebottle/settings/base.py, bluebottle/statistics/statistics.py, bluebottle/test/utils.py, bluebottle/utils/admin.py, bluebottle/utils/exchange_rates.py
So far it was only possible to convert to or from the default usd
currency.
We added a function that first converts to the base currency, and than
does the acctual conversion. This way it will always work.
If applicable
=> Convert from and to any currency

bluebottle/utils/email_backend.py, bluebottle/utils/tests/test_unit.py
=> Fix unicode error in mail sending

bluebottle/statistics/statistics.py, bluebottle/statistics/tests/test_unit.py
=> Also count matching total for open and partial activities

bluebottle/funding/effects.py, bluebottle/funding_stripe/tests/test_states.py
=> Check/test that funding activities get auto submitted or not.

bluebottle/funding_stripe/tests/test_webhooks.py, bluebottle/funding_stripe/views.py
=> Do not fail on non-payment intent refund webhooks

bluebottle/time_based/messages.py, bluebottle/time_based/templates/mails/messages/activity_base.txt, bluebottle/time_based/templates/mails/messages/activity_cancelled.html, bluebottle/time_based/templates/mails/messages/activity_cancelled.txt, bluebottle/time_based/templates/mails/messages/activity_expired.html, bluebottle/time_based/templates/mails/messages/activity_expired.txt, bluebottle/time_based/templates/mails/messages/activity_rejected.html, bluebottle/time_based/templates/mails/messages/activity_rejected.txt, bluebottle/time_based/templates/mails/messages/activity_succeeded.html, bluebottle/time_based/templates/mails/messages/activity_succeeded.txt, bluebottle/time_based/templates/mails/messages/activity_succeeded_manually.html, bluebottle/time_based/templates/mails/messages/activity_succeeded_manually.txt, bluebottle/time_based/templates/mails/messages/date_changed.html, bluebottle/time_based/templates/mails/messages/date_changed.txt, bluebottle/time_based/templates/mails/messages/deadline_changed.html, bluebottle/time_based/templates/mails/messages/deadline_changed.txt, bluebottle/time_based/templates/mails/messages/participant_added.html, bluebottle/time_based/templates/mails/messages/participant_added.txt, bluebottle/time_based/templates/mails/messages/participant_created.html, bluebottle/time_based/templates/mails/messages/participant_created.txt, bluebottle/time_based/tests/test_triggers.py
Fix mail templates.
If applicable
=> Only show impact message in succeeded notification if impact is enabled.

bluebottle/activities/effects.py, bluebottle/activities/states.py, bluebottle/fsm/admin.py, bluebottle/initiatives/serializers.py, bluebottle/initiatives/tests/test_api.py, bluebottle/notifications/templates/admin/notification_effect.html, bluebottle/time_based/effects.py, bluebottle/time_based/models.py, bluebottle/time_based/periodic_tasks.py, bluebottle/time_based/states.py, bluebottle/time_based/tasks.py, bluebottle/time_based/templates/admin/transition_durations.html, bluebottle/time_based/tests/test_periodic_tasks.py, bluebottle/time_based/tests/test_states.py, bluebottle/time_based/tests/test_triggers.py, bluebottle/time_based/triggers.py
Fix succeeding / failing and resetting of time contributions on various
transtions.
Fix creating and succeeding contributions on period participants.
If applicable
=> Fix rendering of timecontribution transitions.

bluebottle/time_based/serializers.py
=> Make is_online not required anymore in the serializer

bluebottle/time_based/models.py
=> Mark is_online as required for activity slots

bluebottle/time_based/effects.py, bluebottle/time_based/tests/test_triggers.py, bluebottle/time_based/triggers.py
period contributions
Fix and test rescheduling time contributions when slot start or duration
changes.
If applicable
=> Reschedule time contributions when change the start and deadline of

bluebottle/files/serializers.py
I have no idea how that could happen, but it does and breaks.
This has the weird side-effect that the link of the image will point to
the id of the first related object instead of the current. But fixing it
properly is not really possible now.
If applicable
=> Do not error when an image is related to multiple objects.

bluebottle/time_based/messages.py, bluebottle/time_based/templates/mails/messages/changed_single_date.html, bluebottle/time_based/templates/mails/messages/changed_single_date.txt, bluebottle/time_based/templates/mails/messages/partial/slots.html, bluebottle/time_based/templates/mails/messages/partial/slots.txt, bluebottle/time_based/templates/mails/messages/reminder_single_date.html, bluebottle/time_based/templates/mails/messages/reminder_single_date.txt, bluebottle/time_based/tests/test_periodic_tasks.py, bluebottle/time_based/tests/test_triggers.py
=> Fix timezone displays in date activity mails

bluebottle/activities/templates/mails/messages/matching_activities.html
- when there is no expertise show default label
- add styling incomplete profile block
- some padding and margin fixes
If applicable
=> Email improvement

bluebottle/members/serializers.py, bluebottle/members/tests/test_api.py
=> Return correct error when creating user with invalid email adres

bluebottle/auth/middleware.py, bluebottle/members/tests/test_api.py, bluebottle/members/utils.py, bluebottle/settings/base.py
Fix RefreshTokenMiddleware. Make sure we an refresh tokens after
issuing.
If applicable
=> Add possibility to override jwt token expiration in tenant settings.

bluebottle/initiatives/tests/test_admin.py, bluebottle/utils/templates/django/forms/widgets/input_option.html
=> Show labels for mutliple select checkboxes in admin

bluebottle/clients/tests/test_api.py, bluebottle/clients/views.py
=> Do not return configuration when platform is closed and user is not

bluebottle/initiatives/tests/test_api.py, bluebottle/initiatives/tests/test_states.py, bluebottle/organizations/models.py
=> Make organization fields except for name optional

bluebottle/files/serializers.py, bluebottle/time_based/tests/test_api.py
Internal Server Error: /api/time-based/period/850/participants
MultipleObjectsReturned at /api/time-based/period/850/participants
get() returned more than one PeriodParticipant -- it returned 2!
https://onepercentclub.atlassian.net/browse/BB-18915
=> Make sure we don't get errors with duplicated files

bluebottle/initiatives/tests/test_admin.py, bluebottle/notifications/admin.py
=> Test initiative admin with wrong id doesn't crash

bluebottle/time_based/triggers.py
slots.
BB-19108 #fixes
If applicable
=> Make sure that activity finishes when all participants are in other

bluebottle/time_based/serializers.py
=> Only retrieve contributions for period participant if duration period is

bluebottle/initiatives/documents.py, bluebottle/initiatives/filters.py, bluebottle/initiatives/tests/test_api.py
=> When sorting on activity date, sort on activity status first.

bluebottle/time_based/tests/test_scenarios.py, bluebottle/time_based/triggers.py
Persoon A meldt zich aan voor Slot X en Y
Als is daarmee Slot X vol (we gaan vanuit dat ie het laatste plekje had)
Persoon A meldt zich af voor Slot X, maar blijft aangemeld voor Y
Slot X is dan weer open
Persoon B meldt zich aan voor Slot X en Y (of Z)
Slot X gaat dan weer naar vol
Persoon B meldt zich af voor Slot X, maar blijft aangemeld voor Y (of Z)
Bug: Slot X gaat niet naar open
=> Fix an edge case for slot participants

bluebottle/time_based/serializers.py, bluebottle/time_based/tests/test_api.py, bluebottle/time_based/views.py
=> Make sure we load the complete participant when applying

bluebottle/segments/models.py, bluebottle/segments/tests/test_unit.py
Use WCAG20 guidelines to select the right color
BB-19511 #resolve
If applicable
=> Prefer white when selecting text_color.

bluebottle/bb_accounts/views.py, bluebottle/members/tests/test_api.py
=> Make signup token expire after 24 hours

bluebottle/activities/tests/test_api.py, bluebottle/utils/filters.py
This way the score of search query of some succeeded activities will not but them above
open activity.
=> Boost search query much less.

bluebottle/scim/serializers.py, bluebottle/scim/tests/test_api.py
=> Ignore duplicate emails in scim when user does not have a

bluebottle/auth/tests/test_api.py, bluebottle/bb_accounts/views.py, bluebottle/members/tests/test_api.py
This prevents csrf attacks where the attacker can secretly log the user
in.
=> Only allow json content type for login endpoint.

bluebottle/activities/utils.py, bluebottle/time_based/serializers.py
This way we do not replace the full model with the list model if you are
a participant looking at the details page.
=> Use the full activity serializer when loading period participants.

bluebottle/activities/models.py, bluebottle/time_based/triggers.py
Do not send team_participant_added message to all members when adding a
team.
=> Make it possible to add teams without an owner to activities.

bluebottle/segments/serializers.py, bluebottle/segments/tests/test_api.py, bluebottle/segments/urls/api.py, bluebottle/segments/views.py
type list.
For platforms with a lot segments this greatly improves the loading time
of the search page or required fields modal.
=> Use hyperlink field instead of including all segments in the segment

bluebottle/initiatives/models.py
Since the frontend now always filters on status, we no longer show the
filter and no longer have a need for this option.
=> Remove status from activity filter types.

bluebottle/cms/models.py
In the current implementation the label "Picture / Text ratio" doesn't correspond with the listed ratio in the options. This PR fixes that
=> chore: fix ratio text

bluebottle/time_based/tests/test_triggers.py, bluebottle/time_based/triggers.py
This caused slots to fill up to quickly when there were withdrawn participants.
=> Only count registered slot particpants when locking slot.

bluebottle/activities/admin.py, bluebottle/clients/signals.py
queue.
This should reduce the number of celery task we create for indexing by a lot.
=> Check if a model is related to a document before adding a task to the

bluebottle/time_based/serializers/participants.py, bluebottle/time_based/views/participants.py
information that should not be available to users that can see participants.
=> Do not include registrations in participants. This might leak

bluebottle/activities/tasks.py, bluebottle/activities/tests/test_tasks.py, bluebottle/time_based/models.py, bluebottle/time_based/signals.py
Since registrations contain personal information the table, instead of first removing the user, we delete the complete registration.
=> Anonimize anonimize-registrations
